Wikia/selenium-tests

pom.xml
pomFailed.xml
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/interactivemaps/PalantirComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/visualeditor/VisualEditorPageObject.java

As Selenium webdriver no longer supports this package as or 2.4x

QAART-470: Removed the dependency of org.json

---

src/test/java/com/wikia/webdriver/common/contentpatterns/URLsContent.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/monetizationmodule/MonetizationModuleComponentObject.java
src/test/java/com/wikia/webdriver/testcases/monetizationtests/monetizationmodule/MonetizationModuleTests.java

Monetization (MON-268):
- add tests for enabling slots for select criteria
- set test wiki and article page

Monetization (MON-268): MonetizationModule - added tests for enabling slots for select criteria

---

src/test/java/com/wikia/webdriver/common/contentpatterns/MercuryContent.java
src/test/java/com/wikia/webdriver/common/core/configuration/POMConfiguration.java
src/test/java/com/wikia/webdriver/common/driverprovider/NewDriverProvider.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/mercury/InteractiveMapsMercuryComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/MercuryBasePageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/ArticlePageTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/CommentsTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/GalleryTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/InteractiveMapsTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/LightboxTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/SmartBannerTests.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

I need Mercury 002 up to date with Mercury 001

Mercury 002 <-- Mercury 001

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/monetizationmodule/MonetizationModuleComponentObject.java
src/test/java/com/wikia/webdriver/testcases/monetizationtests/monetizationmodule/MonetizationModuleTests.java

Monetization (MON-285):
- add tests for testing new visual treatments for AdSense units
- updated functions to verify width for AdSense units
(replace https://github.com/Wikia/selenium-tests/pull/457)

Monetization (MON-285): MonetizationModule - added tests for testing new visual treatments for AdSense units

---

src/test/java/com/wikia/webdriver/common/contentpatterns/PageContent.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/SpecialNewFilesPageObject.java
src/test/java/com/wikia/webdriver/testcases/imageservingtests/ImageStorageTests.java

https://wikia-inc.atlassian.net/browse/QAART-436

fixing ImageStorage_001_deleteImage test by adding redirect=no parameter

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/dropdowncomponentobject/DropDownComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/signup/SignUpPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/login/SpecialUserLoginPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/preferences/PreferencesPageObject.java
src/test/java/com/wikia/webdriver/testcases/facebooktests/FacebookButtonTests.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

This test checks that FB button exists on the following pages:
-Login drop down
-Special:UserSignup
-Special:UserLogin
-Special:Preferences for logged-in user
-Forced Login modal dialog

UC-190-1 adding testcases for checking for FB button on the page

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/SpecialCssPageObject.java

test per https://wikia-inc.atlassian.net/browse/QAART-506

testing solution with adding a line

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/mercury/SearchNavSideMenuComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/MercuryArticlePageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/ArticlePageTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/CommentsTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/InteractiveMapsTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/LightboxTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/SEOTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/SearchTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/SmartBannerTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/TopBarTests.java

I had big mess in files after pulling master to mercury-002 which has google style formatting. That is why some files were 'edited' but change was only in formatting.
I fixed some mercury tests with FAIL label above method name.

Google style Fix + Test Fix

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/globalnav/VenusGlobalNavPageObject.java
src/test/java/com/wikia/webdriver/testcases/globalnavigationtests/CompareScreenshotsForHubsMenu.java
src/test/java/com/wikia/webdriver/testcases/globalnavigationtests/TestGlobalSearchInGlobalNav.java
src/test/java/com/wikia/webdriver/testcases/globalnavigationtests/TestHubLinksInGlobalNav.java
src/test/java/com/wikia/webdriver/testcases/globalnavigationtests/TestWikiaLogoInGlobalNav.java

fixing tests in GlobalNav group
- adding GlobalNav  group where needed
- removing it from imageComparision test, simplifing the test.
- fixing search dropdown selector
Purpose: we want GlobalNav group to be added to common Jenkins suite

Con 2400 fix global search test

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/monetizationmodule/MonetizationModuleComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java
src/test/java/com/wikia/webdriver/testcases/monetizationtests/monetizationmodule/MonetizationModuleTests.java

Monetization (MON-348): update tests for checking module width in MonetizationModule

Monetization (MON-348): MonetizationModule - updated tests for checking module width

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java
src/test/java/com/wikia/webdriver/testcases/globalnavigationtests/GameStarLogo.java
src/test/java/com/wikia/webdriver/testcases/globalnavigationtests/GlobalNavigationHubLinks.java
src/test/java/com/wikia/webdriver/testcases/globalnavigationtests/GlobalNavigationScrollAction.java
src/test/java/com/wikia/webdriver/testcases/globalnavigationtests/GlobalNavigationSearch.java
src/test/java/com/wikia/webdriver/testcases/globalnavigationtests/GlobalNavigationWikiaLogo.java

adding test for verifying that global navigation is attached
renaming classes to assure naming consistency

finishing test and renaming files for better convention

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/monetizationmodule/MonetizationModuleComponentObject.java
src/test/java/com/wikia/webdriver/testcases/monetizationtests/monetizationmodule/MonetizationModuleTests.java

Monetization (MON-348): update test wiki and verifyWindowWidth() function

Monetization (MON-348): MonetizationModule - updated test wiki

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/modalwindows/FacebookSignupModalComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/facebook/FacebookSettingsPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/preferences/PreferencesPageObject.java
src/test/java/com/wikia/webdriver/testcases/facebooktests/FacebookTests.java
src/test/java/com/wikia/webdriver/testcases/signuptests/SignUpTests.java

-Modified the test case to refer to the proper web elements and the new facebook apps web elements. 
-Removed reference to WIkia app posting policy since it no longer exists.

SOC-191 updating SignUpTests for basic facebook signup

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/vet/VetAddVideoComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorHyperLinkDialog.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorSaveChangesDialog.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/BasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/helpers/AdsComparison.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/editmode/VisualEditModePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/messagewall/NewMessageWall.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/block/SpecialBlockListPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/login/SpecialUserLoginPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/visualeditor/VisualEditorMenu.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/wikipage/WikiArticlePageObject.java
src/test/java/com/wikia/webdriver/testcases/createawikitests/CreateWikiTests_loggedInUser.java
src/test/java/com/wikia/webdriver/testcases/visualeditor/VEAddVideoTests.java
src/test/java/com/wikia/webdriver/testcases/visualeditor/VEGalleryTests.java
src/test/java/com/wikia/webdriver/testcases/visualeditor/VEMediaTests.java

Shadowing fields with a local variable is a bad practice reducing code readability: It makes it confusing to know whether the field or the variable is and should be accessed.
Do not merge until https://github.com/Wikia/selenium-tests/pull/501 is merged.

QAART-459: Address Sonar's major issue: Local variables should not shadow class fields

---

src/test/java/com/wikia/webdriver/testcases/mobile/MobileArticleCommentTests.java
src/test/java/com/wikia/webdriver/testcases/mobile/MobileCategoriesTests.java
src/test/java/com/wikia/webdriver/testcases/mobile/MobileEditModeTests.java
src/test/java/com/wikia/webdriver/testcases/mobile/MobileLoginTests.java
src/test/java/com/wikia/webdriver/testcases/mobile/MobileModalTests.java
src/test/java/com/wikia/webdriver/testcases/mobile/MobileSearchTests.java
src/test/java/com/wikia/webdriver/testcases/mobile/MobileTopbarTests.java

Because you can obtain mercury skin with 50% chance i added beforeMethod where i log in as qatestuser to avoid obtaining mercury skin

Wikiamobile tests fix

---

src/test/java/com/wikia/webdriver/testcases/mediatests/lightboxtests/LightboxTests.java

Removing photos module from right rail
selenium tests update
https://wikia-inc.atlassian.net/browse/CONCF-116

removing photos module check, reorganising tests to proper order

---

src/test/java/com/wikia/webdriver/testcases/mobile/MobileInteractiveMapsTests.java

It's only for two weeks till mercury will be in 100%.
It's small tests and i decided to not separate it to two files, that is why i use Thred.sleep and locating elements inside tests etc.

Small interactive maps tests for wikiamobile skin

---

src/test/java/com/wikia/webdriver/common/contentpatterns/URLsContent.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/modalwindows/FacebookSignupModalComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/facebook/FacebookSettingsPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/signup/AlmostTherePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/signup/SignUpPageObject.java
src/test/java/com/wikia/webdriver/testcases/facebooktests/FacebookTests.java

This test is covering the case where a user signs up for a new account via facebook but doesn't give permission to their email address.

SOC-192 test case for facebook account creation without email access

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/monetizationmodule/MonetizationModuleComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java
src/test/java/com/wikia/webdriver/testcases/monetizationtests/monetizationmodule/MonetizationModuleTests.java

https://wikia-inc.atlassian.net/browse/MON-349

MON-349: Create tests for Amazon Video

---

src/test/java/com/wikia/webdriver/common/clicktracking/events/EventsArticleEditMode.java

https://wikia-inc.atlassian.net/browse/QAART-533

updating event label

---

src/test/java/com/wikia/webdriver/common/properties/Credentials.java
src/test/java/com/wikia/webdriver/common/templates/search/IntraWiki.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/global_navitagtion/NavigationBar.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/global_navitagtion/NotificationsComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/BasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/search/intrawikisearch/IntraWikiSearchPageObject.java
src/test/java/com/wikia/webdriver/testcases/notificationstests/ForumNotificationsTests.java
src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsFollowersMessageTests.java
src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsFollowersResponseTests.java
src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsOwnerTests.java
src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsThreadCreatorTests.java
src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsThreadParticipantTests.java
src/test/java/com/wikia/webdriver/testcases/searchtests/intrawiki/BasicActions.java
src/test/java/com/wikia/webdriver/testcases/searchtests/intrawiki/ExactMatch.java
src/test/java/com/wikia/webdriver/testcases/searchtests/intrawiki/Suggestions.java
src/test/java/com/wikia/webdriver/testcases/searchtests/intrawiki/goSearchFeature.java

developed based on https://wikia-inc.atlassian.net/browse/CONCF-63#
Adding 3 goSearch Tests
Make sure go search is turned off for anon	 
Make sure go search is turned off for logged in	 
Make sure go search is turned on for logged in with preference	 
Make sure go search is activated when choosing a suggestion for anon 
Make sure go search is activated when choosing a suggestion for user

Concf 63 go search

---

src/test/java/com/wikia/webdriver/testcases/mobile/MobileEditModeTests.java
src/test/java/com/wikia/webdriver/testcases/mobile/MobileLoginTests.java
src/test/java/com/wikia/webdriver/testcases/mobile/MobileModalTests.java
src/test/java/com/wikia/webdriver/testcases/mobile/MobileSearchTests.java

I disabled tests because they are failing regularly:
- MobileEdit_002_editAndSummaryRetain
- MobileLogin_005_facebookLogin
- MobileModal_005_positionAfterCloseModal
- MobileSearch_005_SearchPageResults

wikiamobile-tests-disable

---

src/test/java/com/wikia/webdriver/common/contentpatterns/WikiTextContent.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorAddMediaDialog.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorDialog.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorHyperLinkDialog.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorReviewChangesDialog.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorSaveChangesDialog.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorSourceEditorDialog.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/ArticlePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/visualeditor/VisualEditorMenu.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/visualeditor/VisualEditorPageObject.java
src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleCRUDAnonTests.java
src/test/java/com/wikia/webdriver/testcases/visualeditor/VEAddVideoTests.java
src/test/java/com/wikia/webdriver/testcases/visualeditor/VEMediaTests.java
src/test/java/com/wikia/webdriver/testcases/visualeditor/text/VisualEditorEditingTests.java

Also contains VE's USS changes that would fix
VEAddExternalVideoTests_001_AddNonPremiumVid
VEAddExternalVideoTests_002_AddPremiumVid

QAART-542 Fixes for ArticleCRUDAnon_006

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorHyperLinkDialog.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/visualeditor/VisualEditorMenu.java
src/test/java/com/wikia/webdriver/testcases/visualeditor/text/VisualEditorEditingTests.java

Updated the UI mapping and logic for the suggestion since now it's very easy to identify what's the suggestion category vs suggestion result. Now there are less work to determine what's what

VE-1880 Updated the test for link inspector

---

src/test/java/com/wikia/webdriver/testcases/facebooktests/FacebookTests.java
src/test/java/com/wikia/webdriver/testcases/signuptests/SignUpTests.java

Also updated the test to use the correct logout.

QAART-549 Added group names to the depending test. 

---

src/test/java/com/wikia/webdriver/common/dataprovider/VisualEditorDataProvider.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorAddMediaDialog.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorMediaSettingsDialog.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/visualeditor/VisualEditorPageObject.java
src/test/java/com/wikia/webdriver/testcases/visualeditor/VEMediaTests.java

UI mapping update for media settings dialog. Custom size now has two input fields. Updated the test to reflect that.
UI mapping update for context menu

VE-1874 Updating test for media setting

---

src/test/java/com/wikia/webdriver/common/core/annotations/RelatedIssue.java
src/test/java/com/wikia/webdriver/common/logging/PageObjectLogging.java

https://wikia-inc.atlassian.net/browse/QAART-561
This would alleviates the problem of manually changing test method's name to tag a failing test.
```
usage:
@RelatedIssue(issueID = "QAART-561")
```
This would add a hyperlink to the the first row of the log table
e.g. http://screencast.com/t/lEiExmYbOP

QAART-561 Adding @RelatedIssue annotation

---

src/test/java/com/wikia/webdriver/common/logging/PageObjectLogging.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/mercury/InteractiveMapsComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/mercury/LightboxComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/mercury/NavigationSideComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/BasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/BasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/CommentsPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/TableOfContentPageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/ArticlePageTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/CommentsTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/InteractiveMapsTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/LightboxTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationSideTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/SEOTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/SmartBannerTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/TOCTests.java

Changes summary:
- removed fail check <-- QAART-576 fix that problem (already included);
- fixed unhandled exception from loading spinner;
- added PageObjectLogging::logWarning() method, which adds yellow line to log;
- added PageObjectLogging::log() method, which will log different message on success and fail to log;
- added BasePageObject::waitForElementVisibleByElement() method, which will wait declared time;
- replaced logging with if..else to new log() method;

Fix to PR #616

---

src/test/java/com/wikia/webdriver/common/contentpatterns/InteractiveMapsContent.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/interactivemaps/InteractiveMapPageObject.java
src/test/java/com/wikia/webdriver/testcases/interactivemapstests/NonSpecificMapTests.java

This test check get response from ponto. We use this response in mobile community apps.

[Mobile Apps] Test ponto request in interactive maps service

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/mercury/SmartBannerComponentObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/SmartBannerTests.java

New social bar is on top of smart banner, i added waiter for social bar to be hidden.

Mercury test fix

---

src/test/java/com/wikia/webdriver/testcases/globalnavigationtests/GlobalNavigationWikiaLogo.java

This PR should be merged when CONCF-430 hits preview

CONCF-430 issue is fixed, let's remove the annotation

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/ArticlePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/BasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/CommentsPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/TableOfContentPageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/CommentsTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/SmartBannerTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/TOCTests.java

Changes summary:
- change selectors name
- add cache buster to url (?cb=timestamp)
- combine two method for navigating through wiki on Mercury (using urlBuilder)
- add wait method for comments test
- add temporary solution for [HG-612](https://wikia-inc.atlassian.net/browse/HG-612) issue

Mercury tests fix

---

src/test/java/com/wikia/webdriver/testcases/chattests/ChatTests.java
src/test/java/com/wikia/webdriver/testcases/chattests/ChatTestsStaff.java

Disalbing chat from sandboxes. It is always failing on devbox

disabling chat from sandboxes

---

src/test/java/com/wikia/webdriver/common/core/imageutilities/ImageComparison.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/LightboxTests.java

Summary of changes:
- Add overloaded method ``public boolean areFilesTheSame(File file1, File file2, double accuracy){...}``
- change return statement to inline version in ``ImageComparison.java``
- change Mercury test to use new method

Improvements

---

src/test/java/com/wikia/webdriver/common/core/urlbuilder/UrlBuilder.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestUrlBuilder.java

- add exception for sandbox-mercurydev

add exception to urlBuilder

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/facebook/FacebookSettingsPageObject.java

Fix for Facebook automation defects SOC-823
NB this fixes only fixes SOC-823 not SOC-774 my mistake, so ignore branch name and please CR and merge.

Fix for Facebook automation defects SOC-823

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsAmazonObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/mobile/MobileAdsBaseObject.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAmazonAds.java

Since we want to rollout AmazonMatch to Mercury we want an automation test for it which was done in https://github.com/Wikia/selenium-tests/pull/665 Below is another test for second part of the story - checking if there is no Amazon ads with next page views if once the ads were displayed.
Connected application changes: https://github.com/Wikia/app/pull/7425

ADEN-2044 Amazon on Mercury tests - part 2

---

src/test/java/com/wikia/webdriver/common/contentpatterns/MercuryArticles.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/mercury/NavigationSideComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/ArticlePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/BasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/CommentsPageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/ArticlePageTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/InteractiveMapsTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/LightboxTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationSideTests.java

This is beginning, i will update status using labels.
Please don't merge it i will do this when time comes.

Create more tests for mercury

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsKruxObject.java

Please merge this PR after changes from https://github.com/Wikia/app/pull/7565 will be released

ADEN-2072 Fixed div id after GptHelper refactor

---

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsScreenshotComparison.java

* Added country check to desktop screenshot comparison tests
* Added Ads_Screenshot_Rapid_CA group for testing Canada using Rapid VPN
* Added Ads_Screenshot_Rapid_DE group for testing Germany using Rapid VPN
* Added Ads_Screenshot_Rapid_GB group for testing United Kingdom using Rapid VPN
* Reformatted TestAdsScreenshotComparison and ordered the methods

ADEN-2180 Testing RapidVPN from GeoEdge

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mobile/MobileBasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mobile/MobileSignupPageObject.java
src/test/java/com/wikia/webdriver/testcases/mobile/MobileSignupTests.java

basic registration testcase, enter all valid data and register success case.

first basic mobile registration happy-path testcase

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mobile/MobileBasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mobile/MobileSignupPageObject.java
src/test/java/com/wikia/webdriver/testcases/mobile/MobileSignupTests.java

Covered
-username in use
-password matches username
-email already taken
-too young user (birthdate error)

SOC-996 adding testcases for error cases in mobile registration

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsAmazonObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAmazonAds.java

* workaround Mercury weird behavior and starting the tests on `SyntheticTests/Amazon_amzn_debug_mode=1` page,
* added verification of GPT slot params,
* added waiting for page title to change before checking slots.

ADEN-2126 Stabilise amazon tests

---

src/test/java/com/wikia/webdriver/common/contentpatterns/MercuryArticles.java
src/test/java/com/wikia/webdriver/common/contentpatterns/MercuryMessages.java
src/test/java/com/wikia/webdriver/common/core/urlbuilder/UrlBuilder.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/CuratedPageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/CuratedMainPageTests.java

Check functionality:
* check if url is on /
* check visibility of:
* * title
* * stats
* * feature content
* * curated content
* * trending articles
* * trending videos
* check correct elements order

CONCF-830 | add mercury cct01

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/filepage/FilePagePageObject.java
src/test/java/com/wikia/webdriver/testcases/imageservingtests/ImageServingTests.java
src/test/java/com/wikia/webdriver/testcases/mediatests/lightboxtests/LightboxTests.java

Test now selects 3rd video in carousel instead of first

Workaround to fix CONCF-763 as Content Team won't fix

---

src/test/java/com/wikia/webdriver/common/contentpatterns/MercuryArticles.java
src/test/java/com/wikia/webdriver/common/contentpatterns/MercuryWikis.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/CuratedMainPageTests.java

Jira: https://wikia-inc.atlassian.net/browse/CONCF-840
CCT04 checks:
* visibility of:
* * title
* * stats
* * feature content
* * curated content
* * trending articles
* invisibility of:
* * trending videos
CCT05 checks:
* visibility of:
* * title
* * stats
* * feature content
* * curated content
* invisibility of:
* * trending articles
* * trending videos

CONCF-840 | add cct04, add cct05, add place for mercury wikis

---

src/test/java/com/wikia/webdriver/testcases/adstests/TestNoAdsOnAdFreeWikis.java

that after removing functionality of HighValueCountry is not needed anymore

removing old test 

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java
src/test/java/com/wikia/webdriver/testcases/logintests/ForgottenPasswordTests.java

Improved Forgotten password tests to delete emails before requesting forgotten password rather than afterwards ;)

Improved Forgotten password tests to delete emails before requesting password

---

src/test/java/com/wikia/webdriver/common/contentpatterns/MercurySubpages.java
src/test/java/com/wikia/webdriver/common/core/url/UrlChecker.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/BasePageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/curatedcontenttests/NavigationTests.java

Algorithm:
* open http://mercurycc.wikia.com/main/category/Templates
* check that you are on category page
* open http://mercurycc.wikia.com/main/section/Categories
* check that you are on section page
* open http://mercurycc.wikia.com/main/section/qwerty
* check that you were redirected to /
* open http://mercurycc.wikia.com/main/category/qwerty
* check that you were redirected to /

CONCF-800 | add test CCT09

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/LoginPage.java
src/test/java/com/wikia/webdriver/testcases/mobile/mercury/Login.java

- x button takes user to proper url
- changes in creating /login page

SOC-984 close button on login

---

src/test/java/com/wikia/webdriver/testcases/imageservingtests/ImageServingTests.java

Added @Execute(asUser = User.USER)

Patrick24 jul 15

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/BasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/SignupPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mobile/MobileBasePageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/LoginTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/SignupTests.java

https://wikia-inc.atlassian.net/browse/SOC-1104

update test cases to execute only for mobileregressiontesting wikia

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/SearchPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/search/intrawikisearch/IntraWikiSearchPageObject.java

fixes for Stale element exception
it still needs more work
Needs a fix for method verifyLastResultPage in IntraWikiSearchPageObject which has messy logic and fails

fixing pagination test

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdTypeDataProvider.java
src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
src/test/java/com/wikia/webdriver/common/dataprovider/ads/GermanAdsDataProvider.java
src/test/java/com/wikia/webdriver/common/dataprovider/mobile/MobileAdsDataProvider.java

We're releasing three verticals mapping for DFP paths. It breaks some tests and in this pull request we fix them.

ADEN-2297 Three musketeers

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/LoginTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/SignupTests.java
src/test/java/com/wikia/webdriver/testcases/signuptests/SignUpTests.java

https://wikia-inc.atlassian.net/browse/SOC-1163
add japanese user login and signup tests to mercury login/reg test cases.

add japanese user login and signup to mercury tests

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsFloorAdhesionObject.java

Re-named CSS selectors so the tests look for the right stuff.

ADEN-2336 Fixed Oasis floor adhesion tests

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/SignupPageObject.java

@tomasznapieralski @ludwikkazmierczak @justnpT @qaga @kvas-damian This should make Jenkins happy.

Update error messages for mercury signup

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/GermanAdsDataProvider.java

We changed the way how SOI* are generated:
https://github.com/Wikia/app/pull/8111
and it required changes in our data provider.

ADEN-2335 Reflect recent changes in 71Media integration

---

config_sample.yml
readme.md
src/test/java/com/wikia/webdriver/common/core/url/UrlBuilder.java
src/test/java/com/wikia/webdriver/common/driverprovider/NewDriverProvider.java
src/test/java/com/wikia/webdriver/common/driverprovider/mobileprovider/MobileDriverProvider.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestUrlBuilder.java

/cc @drets @PiotrGackowski - is it breaking ads tests?

CONCF-641 | remove CHROMEMOBILE and ?useskin=wikiamobile

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/GermanAdsDataProvider.java

Changed data provider after last vertical mapping changes.

ADEN-2225 Fix ads-71media-params job

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/BasePageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/TOCTests.java

Algorithm TOCT03:
- navigate to article with TOC and with `#id` in url
- check that page was scrolled to proper header
Algorithm TOCT04:
- navigate to article with TOC
- click on link with redirection to current article with `#id` in link
- check that page was scrolled to proper header
Algorithm TOCT05:
- navigate to article without TOC
- click on link with redirection to article with TOC with `#id` in link
- check that page was scrolled to proper header

HG 844 | add TOCT03, TOCT04, TOCT05

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java

Data provider change to reflect code changes.

ADEN-2359 Changed wka targetting for corp pages

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/modalwindows/CreateArticleModalComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/wikitextshortcuts/WikiTextShortCutsComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/PortableInfoboxPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/ArticlePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/editmode/SourceEditModePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/category/CategoryPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/SpecialWhatLinksHerePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/themedesigner/SpecialThemeDesignerPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/template/TemplatePageObject.java
src/test/java/com/wikia/webdriver/testcases/portableinfoboxtests/PortableInfoboxTests.java

Refactoring Portable Infobox tests

Dat 3091 - refactoring

---

src/test/java/com/wikia/webdriver/common/core/elemnt/Wait.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/modalwindows/CuratedContentToolModal.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/ArticlePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/oasis/MainPage.java
src/test/java/com/wikia/webdriver/testcases/oasismainpage/CuratedContentTool.java

Reverts Wikia/selenium-tests#823

Revert "Revert "CONCF-1073""

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/search/intrawikisearch/IntraWikiSearchPageObject.java

I've improved one really unreadable loop into more readable form, without changing its logic

Improve verification loop

---

src/test/java/com/wikia/webdriver/common/core/MailFunctions.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/globalnav/VenusGlobalNavPageObject.java

fixing stale-element reference exception in HubTests
and
improving messages in mail funtion

fixing stale-element reference exception in HubTests

---

src/test/java/com/wikia/webdriver/common/contentpatterns/MercurySubpages.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/curatedcontenttests/MainPageTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/curatedcontenttests/NavigationTests.java

**Merge when XW-171 is merged to dev in Mercury**
/cc @justnpT @tomasznapieralski

XW-171 load sections ond categories on root path - adjust tests

---

src/test/java/com/wikia/webdriver/testcases/activityfeedstests/WikiActivityTests.java

Changed 'Avtivity' to 'Activity' in several places.

Fixed Typos

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
src/test/java/com/wikia/webdriver/common/dataprovider/ads/GermanAdsDataProvider.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java

Connected to changes from: Wikia/app#8296
* added new test cases to check new key-vals: `s0v` and `s0c`,
* fixed 71Media data in dataprovider after last changes,
* changed formatting in few places.

ADEN-2298 New dfp key val params

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/SpotifyWidgetPageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/widgettests/SpotifyTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/SoundCloudTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/SpotifyTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/WeiboTests.java

https://wikia-inc.atlassian.net/browse/XW-201

XW-201 | add spotify tests

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/PollsnackWidgetPageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/widgettests/PollsnackTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/PollsnackTests.java

Adding test to pollsnack
https://wikia-inc.atlassian.net/browse/XW-273

XW-273 adding tests for pollsnack

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/GoogleFormWidgetPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/PollsnackWidgetPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/SpotifyWidgetPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/TwitterWidgetPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/VKWidgetPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/WeiboWidgetPageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/widgettests/AllTagsTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/widgettests/GoogleFormTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/AllTagsTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/GoogleFormTests.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

https://wikia-inc.atlassian.net/browse/XW-206

XW-206 | Add tests for Google Form

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/GoogleFormWidgetPageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/widgettests/AllTagsTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/widgettests/GoogleFormTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/AllTagsTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/GoogleFormTests.java

https://wikia-inc.atlassian.net/secure/RapidBoard.jspa?rapidView=274&view=detail&selectedIssue=XW-279

XW-352 | enable tests

---

src/test/java/com/wikia/webdriver/common/core/Assertion.java
src/test/java/com/wikia/webdriver/common/core/url/UrlBuilder.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/curatedcontenttests/MainPageTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/curatedcontenttests/NavigationTests.java

XW-251 check if notification is present when redirceting to main page from not existing section

---

src/test/java/com/wikia/webdriver/testcases/logintests/LoginTests.java

added new test for staff to execute @ new login flow

SOC-1250 fix for staff user login

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/mercury/InteractiveMapsComponentObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/InteractiveMapsTests.java

https://wikia-inc.atlassian.net/browse/XW-112
**DON'T MERGE BEFORE XW-112 IS RELEASED TO PROD ON MERCURY**

XW-112 change selector to map

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/mercury/NavigationSideComponentObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationSideTests.java

https://wikia-inc.atlassian.net/browse/XW-289
Related PR: https://github.com/Wikia/mercury/pull/1504

XW-289 adjust tests for local nav in mercury

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/mercury/NavigationSideComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/ArticlePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/BasePageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/ArticlePageTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/CommentsTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationSideTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/widgettests/VKTests.java

https://wikia-inc.atlassian.net/browse/XW-553

XW-553 | fix failing tests

---

src/test/java/com/wikia/webdriver/common/contentpatterns/MercurySubpages.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/curatedcontenttests/EditorTests.java

https://wikia-inc.atlassian.net/browse/XW-479

XW-479 | fix tests

---

src/test/java/com/wikia/webdriver/common/core/elemnt/JavascriptActions.java

catch not supported JS operation exception

---

src/test/java/com/wikia/webdriver/common/core/imageutilities/ImageComparison.java

Fix the image comparison logic and make it possible to compare images with different sizes.

ADEN-2485 Compare images with different sizes

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsTaboolaObject.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsTaboolaOasis.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

Check Taboola unit (below the article and in right rail) on Oasis.

ADEN-2626 Add test for Taboola on Oasis

---

src/test/java/com/wikia/webdriver/common/dataprovider/mobile/MobileAdsDataProvider.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestSlotsMobile.java

We allowed new size of leaderboard on Mercury.
Test updated and leaderboard has the new image.

ADEN-2644 Update image link

---

src/test/java/com/wikia/webdriver/common/core/elemnt/Wait.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/curatedcontent/CuratedMainPagePageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/curatedcontenttests/MainPageTests.java

https://wikia-inc.atlassian.net/browse/XW-728
Also fixed: https://wikia-inc.atlassian.net/browse/XW-209
Invoked 25 times: no exceptions

XW-728 | add check for PAD slot in main page

---

src/test/java/com/wikia/webdriver/common/dataprovider/mobile/MobileAdsDataProvider.java

ADEN-2721 Fix avatar wiki skin assertion

---

pom.xml

This fixes some bugs on Jenkins

Appium update

---

src/test/java/com/wikia/webdriver/common/contentpatterns/MercurySubpages.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/PortableInfoboxObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/PortableInfoboxTests.java

https://wikia-inc.atlassian.net/browse/DAT-3085

DAT-3085 Update collapsed/uncollapsed infobox tests

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsKruxSegments.java

Check only particular segments rather than whole bunch of segments from localStorage.

ADEN-2801 Make Krux seg tests more robust

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsPrefooters.java

Our prefooters tests fails on some machines because of wrong default resolution. This solution may help but may not... we have to check it :japanese_ogre:

ADEN-2811 Set screen size in prefooters test

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/lightbox/LightboxComponentObject.java

There is no longer an Iframe inside lightbox, so I had to change a selector to fix the lightbox test

Changed seletor to match current

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/TableOfContentPageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/TOCTests.java

The methods affected by the change:
MercuryTOCTest_001_TOCPresence_ListRedirection ()
MercuryTOCTest_003_RedirectionToHeaderDirectlyFromLink ()
MercuryTOCTest_004_RedirectionToHeaderFromCurrentPage ()
MercuryTOCTest_005_RedirectionToHeaderFromOtherPage ()
The tests were verfified on the functional level
The tests were verified on the local stability level
https://wikia-inc.atlassian.net/browse/XW-909

changing pixel verification into visibility verification

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java

Change special page name in order to avoid redirect in the tests

change special page name in the provider

---

src/test/java/com/wikia/webdriver/common/core/geoedge/CountryCode.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsEvolveObject.java
src/test/java/com/wikia/webdriver/testcases/adstests/Test71MediaAds.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsEvolveMercury.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsEvolveOasis.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsOnCorporatePages.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsScreenshotComparisonMobile.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestNoAdsLoggedInUsers.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestNoAdsOnAdFreeWikis.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

Extend Evolve2 tests to Mercury skin

ADEN-2830 Add tests for Evolve2 on Mercury

---

src/test/java/com/wikia/webdriver/testcases/discussions/Layout.java
src/test/java/com/wikia/webdriver/testcases/discussions/Navigating.java
src/test/java/com/wikia/webdriver/testcases/discussions/Sharing.java
src/test/java/com/wikia/webdriver/testcases/discussions/Sorting.java
src/test/java/com/wikia/webdriver/testcases/discussions/Upvoting.java

XW-1045 disable not stable tests

---

src/test/java/com/wikia/webdriver/common/core/CommonUtils.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/editmode/VisualEditModePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/wikipage/editmode/WikiArticleEditMode.java

Deleted a dirty hack for copy-paste from system clipboard. Deleted unused methoda. All affected tests are working on Jenkins builds.

Deleted method for putting content to system clipboard

---

src/test/java/com/wikia/webdriver/common/skin/Skin.java
src/test/java/com/wikia/webdriver/common/skin/SkinHelper.java
src/test/java/com/wikia/webdriver/elements/mercury/Category.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/CategoryTest.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationTest.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

https://wikia-inc.atlassian.net/browse/XW-57

XW-57 | add category test for Mercury

---

src/test/java/com/wikia/webdriver/common/templates/NewTestTemplate.java
src/test/java/com/wikia/webdriver/common/templates/NewTestTemplateCore.java
src/test/java/com/wikia/webdriver/elements/mercury/Navigation.java
src/test/java/com/wikia/webdriver/elements/mercury/SmartBanner.java

**DON'T MERGE**
NEEDS TO BE MERGED AFTER MERCURY RELEASE
https://wikia-inc.atlassian.net/browse/XW-980

XW-980 | adjust selectors after navigation clean up in Mercury

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationTest.java

I analyzed the test cases and improved their names as part of https://wikia-inc.atlassian.net/browse/XW-980

improving test case name in global navigation on mercury

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
src/test/java/com/wikia/webdriver/common/dataprovider/mobile/MobileAdsDataProvider.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestDfpParamsPresent.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestDfpParamsPresentMobile.java

Add test for Rubicon Fastlane param.
**Please, don't merge it before mercury release (https://github.com/Wikia/mercury/pull/1902)**

ADEN-2826 Add test for Fastlane param

---

src/test/java/com/wikia/webdriver/elements/mercury/old/PortableInfoboxObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/CategoryTest.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationTest.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/SmartBannerTest.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/ArticlePageTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/CommentsTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/LightboxTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/PortableInfoboxTests.java

https://wikia-inc.atlassian.net/browse/XW-1008

improving test case names and one method name

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java

follow up to https://github.com/Wikia/selenium-tests/pull/1000

log mercury user id

---

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsMonitoringOasis.java

Fixes error when country code returns "null"

Oasis gef ads fix

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdType.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsFloatingMedrecOasis.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsSynthetic.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

Add tests for floating medrec.
Merge after https://github.com/Wikia/app/pull/9726

ADEN-2840 Add FMR tests

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/old/ArticlePageTests.java

XW | fix selector

---

src/test/java/com/wikia/webdriver/testcases/signuptests/SignUpTests.java

https://wikia-inc.atlassian.net/browse/QAART-745

update related issue to signup test

---

src/test/java/com/wikia/webdriver/testcases/signuptests/SignUpTests.java

https://wikia-inc.atlassian.net/browse/QAART-744

adding related issue to japanese login test

---

src/test/java/com/wikia/webdriver/elements/mercury/old/CommentsPageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/CommentsTests.java

XW-1222 wait for comments to load

---

src/test/java/com/wikia/webdriver/common/contentpatterns/URLsContent.java

DO NOT MERGE YET!
https://wikia-inc.atlassian.net/browse/DAT-3843
merge after: https://github.com/Wikia/app/pull/9840 hit the prod

DAT-3843 change SPECIAL_INFOBOX_BUILDER url

---

src/test/java/com/wikia/webdriver/testcases/infoboxbuilder/InfoboxBuilderTests.java
src/test/java/com/wikia/webdriver/testcases/portableinfoboxtests/PortableInfoboxTests.java

We want to make this tests run in jenkins jobs.
@tomasznapieralski

DAT-3867 add group InfoboxBuilderTests

---

src/test/java/com/wikia/webdriver/testcases/chattests/ChatTests.java
src/test/java/com/wikia/webdriver/testcases/chattests/ChatTestsStaff.java
src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsFollowersMessageTests.java
src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsFollowersResponseTests.java
src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsOwnerTests.java
src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsThreadCreatorTests.java
src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsThreadParticipantTests.java

* Added common group for all notifications tests
* Added common group for all chat tests
Checked on Jenkins, pre- and post-release jobs doesn't use groups I added, so running tests won't be duplicated.

Added group for every notifications tests

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/TwitterWidgetPageObject.java

This pull request makes seven tests happier on Mercury like [here](http://jenkins:8080/view/Mercury/job/Mercury-TESTS-Emulators-alternative/134/console). Probably same amount for Oasis.

fixes selector for div in Twitter widget

---

src/test/java/com/wikia/webdriver/elements/mercury/old/MercuryFooterComponentObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/RedirectionTests.java

http://jenkins.wikia-prod:8080/view/Mercury%20Backgroud%20Tasks/job/Mercury-TEST-emulator/11285/
@azarek

Fix mercury tests

---

src/test/java/com/wikia/webdriver/common/contentpatterns/MercurySubpages.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/curatedcontenttests/EditorTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/curatedcontenttests/NavigationTests.java

XW | mark tests with related issue and fix typos

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/old/LoginTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/RedirectionTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/SignupTests.java

update failing tests with issueIds in JIRA

XW | release 223

---

src/test/java/com/wikia/webdriver/elements/oasis/pages/InfoboxBuilderPage.java
src/test/java/com/wikia/webdriver/testcases/infoboxbuilder/InfoboxBuilderTests.java

fixing problem with confirmation dialog popping up after user logs in

Dat ib refactor

---

src/test/java/com/wikia/webdriver/elements/mercury/old/CommentsPageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/CommentsTests.java

XW-1283 expect oasis not wikia mobile

---

src/test/java/com/wikia/webdriver/elements/oasis/pages/InfoboxBuilderPage.java

Change due to DAT-4015 rearranging add buttons on Infobox sidebar

Rearrange add buttons

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/AuthModal.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/global_navitagtion/NavigationBar.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java
src/test/java/com/wikia/webdriver/testcases/logintests/ForgottenPasswordTests.java
src/test/java/com/wikia/webdriver/testcases/logintests/LoginTests.java

Revert SOC-1496

---

build.gradle
src/test/java/com/wikia/webdriver/common/core/Helios.java
src/test/java/com/wikia/webdriver/common/core/drivers/browsers/HtmlUnitBrowser.java
src/test/java/com/wikia/webdriver/common/properties/HeliosConfig.java

+ Bumped up selenium version to 2.53.0
+ Deleted unused headers (client_id and client_secret) from Helios call
+ HTMLUnit driver was moved to be a selenium subproject, adapted this change by adding a separate dependency

Bumped up selenium version and Removed unused headers from Helios 

---

src/test/java/com/wikia/webdriver/elements/mercury/old/ArticlePageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/ArticlePageTests.java

XW | remove unused methods and look for avatar on oasis not wikiamobile

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/helpers/AdsFloorAdhesionSkinContext.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestFloorAdhesion.java

In order to make our synthetic tests more stable we want to run them on project43 wiki.

ADEN-3148 Moved floor adhesion tests to project43 wiki

---

src/test/java/com/wikia/webdriver/elements/mercury/old/LoginPageObject.java

wait until stability is proved:
http://jenkins:8080/view/Maintenance/job/test-stability-check/24/

changing selector of registration link

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsTrackingPixels.java

XW-1282 add test case for checking curated main pages subpages

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/helpers/AdsFloorAdhesionSkinContext.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestFloorAdhesion.java

In order to have separate jobs for feature per skin we have to change the groups.
Related pull request: https://github.com/Wikia/jenkins-jobs/pull/12.

ADEN-3176 Changed floor adhesion tests groups

---

src/test/java/com/wikia/webdriver/elements/mercury/old/GalleryComponentObject.java

XW | fix selector after disabling wgSeoFriendlyImages

---

src/test/java/com/wikia/webdriver/elements/mercury/old/InteractiveMapsComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/article/OasisFooterComponentObject.java

XW-1287 | fix tests

---

src/test/java/com/wikia/webdriver/common/core/elemnt/JavascriptActions.java
src/test/java/com/wikia/webdriver/common/core/url/Page.java
src/test/java/com/wikia/webdriver/common/core/url/UrlBuilder.java
src/test/java/com/wikia/webdriver/common/dataprovider/MercurySEODataProvider.java
src/test/java/com/wikia/webdriver/elements/common/Navigate.java
src/test/java/com/wikia/webdriver/elements/mercury/components/Head.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/BasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/wam/WamPageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/HTMLTitleTests.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

XW-1370 add tests for document title

---

src/test/java/com/wikia/webdriver/elements/mercury/old/PortableInfoboxObject.java

infobox-test-fix | fix mercury_infobox_infoboxSizeIsNotAffectedByClickOnImages

---

src/test/java/com/wikia/webdriver/elements/common/Navigate.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/RecentWikiActivityTest.java

Temporary fix of Recent Activity test because of already running experiment DAT-4052.

Temporary fix of Recent Activity test

---

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsTrackingPixels.java

ADEN Add UseUnstablePageLoadStrategy to pixel test

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/discussions/PostsListPage.java

/cc @justnpT @tomasznapieralski @kvas-damian

Fix Fallout Forum ID

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/discussions/PostsListPage.java

Reverts Wikia/selenium-tests#1148

Revert "Fix Fallout Forum ID"

---

src/test/java/com/wikia/webdriver/elements/common/Navigate.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/RecentWikiActivityTest.java

- URL building for Mercury
- One Recent Activity test
ping @ludwikkazmierczak @tomasznapieralski @drets @justnpT @Archbold

DAT-4081 Restore previous Mercury url building after finished AB test

---

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsTrackingPixels.java

Reverting this commit
https://github.com/Wikia/selenium-tests/commit/4b3218aa6c703a99957bfe811e0686b0ed9bfc5a

ADEN-3258-Temporary revert to old value

---

src/test/java/com/wikia/webdriver/elements/mercury/old/GalleryComponentObject.java
src/test/java/com/wikia/webdriver/elements/mercury/old/PortableInfoboxObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/editmode/MobilePreviewEditModePageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/HTMLTitleTests.java

XW | test adjustments after release

---

src/test/java/com/wikia/webdriver/testcases/discussions/Navigating.java

XW | add related issue

---

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsTrackingPixels.java

Reverts Wikia/selenium-tests#1158

Revert "ADEN-3258-Temporary revert to old value"

---

src/test/java/com/wikia/webdriver/testcases/chattests/ChatTestsStaff.java

Do not run test004 on preview env. It is working as on prod env

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdTypeDataProvider.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsAdXCollapse.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

Check for correct collapse from AdX

Aden 3276 ad x collapse

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/HTMLTitleTests.java

https://wikia-inc.atlassian.net/browse/XW-1442
//cc @Wikia/x-wing

XW-1442 | update test

---

src/test/java/com/wikia/webdriver/common/contentpatterns/MercuryWikis.java
src/test/java/com/wikia/webdriver/elements/mercury/components/Navigation.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationTest.java

testing if hubs in mercury navigation are visible only on english wikis

nav-redesign v2

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/old/RedirectionTests.java

- bug report: https://wikia-inc.atlassian.net/browse/XW-1469
- pending fix: https://wikia-inc.atlassian.net/browse/QAART-773
- task for reenabling the test after fix: https://wikia-inc.atlassian.net/browse/XW-1476

XW-1469 | disabled MercuryRedirectionTest_004_RedirectFromFullSiteToMobile

---

src/test/java/com/wikia/webdriver/testcases/discussions/Layout.java
src/test/java/com/wikia/webdriver/testcases/discussions/Sorting.java
src/test/java/com/wikia/webdriver/testcases/discussions/Upvoting.java

added related issues to 4 tests in discussions

added related issues

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java

SUS | revert breaking change for all tests for logged in users

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/chatpageobject/ChatPage.java
src/test/java/com/wikia/webdriver/testcases/chattests/ChatTests.java
src/test/java/com/wikia/webdriver/testcases/chattests/ChatTestsStaff.java

SUS | get rid of sonar issues

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java

@rogatty @ludwikkazmierczak @idradm @dianafa @rybmat

SUS | check if on mercury skin and if yes wait for ember to start and nav to load

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/old/SignupTests.java

https://wikia-inc.atlassian.net/browse/SER-80
//cc @rogatty

SER-80 | Disable MercurySignupTest_002_signupErrorEmailInUse while validatior is disabled

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/BasePageObject.java

`iframe[title='VisualDNA Analytics']` element does not exists on any page. To wait for page to load I added waiting for Comscore to load as it appears on every page.

Wait for comscore to load

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/AuthModal.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java

- Moved AuthModal to Lombok getter
- code cleanup for AuthModal

Moved AuthModal to Lombok getter

---

src/test/java/com/wikia/webdriver/elements/mercury/components/Navigation.java
src/test/java/com/wikia/webdriver/elements/mercury/components/Search.java
src/test/java/com/wikia/webdriver/elements/mercury/components/SmartBanner.java
src/test/java/com/wikia/webdriver/elements/mercury/components/TopBar.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java
src/test/java/com/wikia/webdriver/testcases/infoboxbuilder/InfoboxBuilderTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationTest.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/SmartBannerTest.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/TopBarTests.java

This reverts commit 60f01c71214579d2ae8091fa74243da48617ff11, reversing
changes made to fd865111958e907fc43f6f8888ce94237784e7e6.
@nikodamn @qaga

Revert "Merge pull request #1201 from Wikia/DAT-4116"

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java

SUS | change wait from present to visible

---

src/test/java/com/wikia/webdriver/testcases/discussions/Layout.java
src/test/java/com/wikia/webdriver/testcases/discussions/Navigating.java
src/test/java/com/wikia/webdriver/testcases/discussions/Sharing.java
src/test/java/com/wikia/webdriver/testcases/discussions/Sorting.java
src/test/java/com/wikia/webdriver/testcases/discussions/Upvoting.java

removed outdated related issues and imports

---

src/test/java/com/wikia/webdriver/elements/mercury/pages/ErrorPage.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/ErrorPageTests.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

DAT-4211 | add test for error page

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/old/curatedcontenttests/NavigationTests.java

Revert this when https://wikia-inc.atlassian.net/browse/DAT-4292 is done

DAT-4292 | disable failing test

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/TopBarTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/InteractiveMapsTests.java

XW | tests adjustments related with recent Mercury release

---

src/test/java/com/wikia/webdriver/elements/mercury/old/MercuryFooterComponentObject.java
src/test/java/com/wikia/webdriver/elements/mercury/old/PortableInfoboxObject.java
src/test/java/com/wikia/webdriver/testcases/discussions/Layout.java
src/test/java/com/wikia/webdriver/testcases/discussions/Navigating.java
src/test/java/com/wikia/webdriver/testcases/discussions/Promoting.java
src/test/java/com/wikia/webdriver/testcases/discussions/Sharing.java
src/test/java/com/wikia/webdriver/testcases/discussions/Sorting.java
src/test/java/com/wikia/webdriver/testcases/discussions/Upvoting.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationTest.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/RecentWikiActivityTest.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/CommentsTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/LoginTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/PortableInfoboxTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/RedirectionTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/SignupTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/TOCTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/curatedcontenttests/EditorTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/curatedcontenttests/NavigationTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/widgettests/TwitterTests.java

https://wikia-inc.atlassian.net/browse/XW-1515

XW-1515 | review mercury tests

---

src/test/java/com/wikia/webdriver/elements/mercury/old/MercuryAlertComponentObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/curatedcontenttests/NavigationTests.java

https://wikia-inc.atlassian.net/browse/DAT-4292
https://github.com/Wikia/mercury/pull/2483 fixed the failing test.
/cc @tomasznapieralski

DAT-4292 | Enable MercuryCuratedNavigationTest_004

---

src/test/java/com/wikia/webdriver/testcases/discussions/Upvoting.java

https://wikia-inc.atlassian.net/browse/SOC-2596
//cc @justnpT @qaga

SOC-2596 | disable failing tests

---

src/test/java/com/wikia/webdriver/elements/mercury/components/Navigation.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationTest.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/TopBarTests.java

Description
Additional test for navigation menu - when clicked 'explore XXX wiki' user is redirected to that wiki's main page.
Reviewers

Dat 4227 = menu navigation: explore wiki clickability test

---

src/test/java/com/wikia/webdriver/elements/mercury/components/Search.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/SearchResultsPage.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/SearchTests.java

https://wikia-inc.atlassian.net/browse/DAT-4474
https://wikia-inc.atlassian.net/browse/DAT-4150
@Wikia/west-wing 
propositions of any additional test cases are welcome

DAT-4474 | Tests for Load More functionality on mercury search result page

---

src/test/java/com/wikia/webdriver/common/core/helpers/ArticlePurger.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/modalwindows/CreateArticleModalComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/PortableInfobox.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/SpecialWhatLinksHerePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/visualeditor/VisualEditorPageObject.java
src/test/java/com/wikia/webdriver/testcases/portableinfoboxtests/PortableInfoboxTests.java

* Add article purging to Portable Infobox tests - introduce ArticlePurger helper
* Refactoring of PortableInfobox component page
Reviewers:

Article purging and refactoring of Portable Infobox tests - DAT-4501

---

src/test/java/com/wikia/webdriver/common/logging/PageObjectLogging.java

What is Sales pitch dialog? See https://wikia-inc.atlassian.net/browse/CE-3768

CE-3769: Disable Sales pitch dialog

---

config_default.yml
src/test/java/com/wikia/webdriver/common/core/annotations/Execute.java
src/test/java/com/wikia/webdriver/common/core/configuration/Configuration.java
src/test/java/com/wikia/webdriver/common/logging/PageObjectLogging.java
src/test/java/com/wikia/webdriver/common/templates/core/CoreTestTemplate.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/communitypage/SalesPitchDialog.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/communitypage/SpecialCommunity.java
src/test/java/com/wikia/webdriver/testcases/communitypagetests/CommunityPageSalesPitchDialogTests.java

Tests for Community Page Sales Pitch Dialog:
- verify that dialog is shown on 4th pageview
- verify that visiting edit page is not counted as pageview
- verify that clicking on button "Help out" redirect you to Special:Community
- verify that if user has seen dialog (cookie is set) it will not appears again

CE-3769: Tests for Community Page Sales Pitch Dialog

---

src/test/java/com/wikia/webdriver/elements/mercury/components/Navigation.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/login/RegisterPage.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/login/SignInPage.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/AuthModal.java
src/test/java/com/wikia/webdriver/testcases/logintests/ForgottenPasswordTests.java

fixed forgotten password tests

---

src/test/java/com/wikia/webdriver/testcases/interactivemapstests/NonSpecificMapTests.java

Block test 010 and 012 for testing on preview environment.

Dont run two tests on preview env

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/AceEditor.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/editmode/SourceEditModePageObject.java
src/test/java/com/wikia/webdriver/testcases/portableinfoboxtests/PortableInfoboxTests.java

this fixes PortableInfoboxTests `verifyCopiedTemplateSyntaxInArticlePresence` test on Jenkins
@lukaszkonieczny

DAT-4569: fix failing Selenium Test

---

src/test/java/com/wikia/webdriver/elements/common/Navigate.java

remove code from finished experiment - changes that were introduced here:
- https://github.com/Wikia/selenium-tests/commit/d9a06d4b8d2be0a9225f2a010debfa8ffc7d385c
- https://github.com/Wikia/selenium-tests/commit/cdbfb1cba1e91be358711ca15ea6274bdbcc31ce
@idradm @SebastianMarzjan

DAT-4487 Cleanup after experiment

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsEvolveObject.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsEvolveOasis.java

Test is removed because it was with Evolve1 solution. Ticket connected is closed as Won't Fix. 
We are not focused so much on Evolve so thats why I removed this test.

ADEN-3521 move evolve tests to project43

---

src/test/java/com/wikia/webdriver/elements/mercury/old/TableOfContentPageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/TOCTests.java

Fix failing test

---

src/test/java/com/wikia/webdriver/testcases/discussions/CreatingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/UpvotingTests.java

added RI to failing tests

---

src/test/java/com/wikia/webdriver/testcases/portableinfoboxtests/PortableInfoboxTests.java

Add purging and change assertion method

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/visualeditor/VisualEditorPageObject.java
src/test/java/com/wikia/webdriver/testcases/portableinfoboxtests/PortableInfoboxTests.java

- Add waiting for element clickable
- Update CSS selector
Reviewers:

Add waiting, minor css selector change

---

src/test/java/com/wikia/webdriver/elements/oasis/pages/TemplateEditPage.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/editmode/SourceEditModePageObject.java
src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleSourceModeTests.java
src/test/java/com/wikia/webdriver/testcases/infoboxbuilder/InfoboxBuilderTests.java
src/test/java/com/wikia/webdriver/testcases/portableinfoboxtests/PortableInfoboxTests.java

- RTE tests: Remove init method
- InfoboxBuilder tests: Remove asserting spinner
- TemplateEditPage: Change implementation of method checking visibility
Reviewers:

Add waiting for cke before getting it's content

---

src/test/java/com/wikia/webdriver/elements/oasis/pages/WikiFeatures.java

Update CSS selectors for Infobox Europa Theme on Special:WikiFeatures after moving Europa Theme below in the features lists.
Reviewers:
@rybmat

Update CSS selectors

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/desktop/PostsCreatorDesktop.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/desktop/ReplyCreatorDesktop.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/mobile/ReplyCreatorMobile.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingReplyTests.java

Reverts Wikia/selenium-tests#1346

Revert "Soc 2602"

---

src/test/java/com/wikia/webdriver/testcases/discussions/CreatingPostTests.java

https://wikia-inc.atlassian.net/browse/SOC-2730

SOC-2730 | disable failing tests

---

src/test/java/com/wikia/webdriver/testcases/discussions/UpvotingTests.java

https://wikia-inc.atlassian.net/browse/SOC-2724

SOC-2724| disable failing tests

---

src/test/java/com/wikia/webdriver/testcases/discussions/SharingTests.java

https://wikia-inc.atlassian.net/browse/MAIN-7562

MAIN-7562 | disable failing test

---

src/test/java/com/wikia/webdriver/testcases/globalshortcuts/ActionExplorerTest.java

Ww globalshortcuts

---

src/test/java/com/wikia/webdriver/testcases/discussions/UpvotingTests.java

https://wikia-inc.atlassian.net/browse/SOC-2724

SOC-2724 | disable failing test

---

src/test/java/com/wikia/webdriver/testcases/communitypagetests/CommunityPageSalesPitchDialogTests.java

To test which is checking if Sales Pitch Dialog is visible on 4th page view add verifying if it is NOT visible on 5th and 6th page view.
Reviewers:

Add checking 5th and 6th page views

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/RecentWikiActivityTest.java

The test is working when run locally and on Jenkins now, so re-enabling
it.
/cc @Wikia/x-wing

(XW-1734) Re-enable Mercury RWA blockedUserOpenDiffPageAndGoBack test

---

src/test/java/com/wikia/webdriver/testcases/portableinfoboxtests/PortableInfoboxTests.java

Moved to FF to solve resolution problem

Moved lightbox test to FF cause of resolution

---

src/test/java/com/wikia/webdriver/common/core/helpers/ArticlePurger.java
src/test/java/com/wikia/webdriver/common/logging/PageObjectLogging.java

- Added logInfo with exception
- Reformatted code

Added logInfo with exception

---

src/test/java/com/wikia/webdriver/common/core/helpers/ArticlePurger.java
src/test/java/com/wikia/webdriver/elements/oasis/components/comment/ArticleComment.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/minieditor/MiniEditorComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/vet/VetOptionsComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorAddMapDialog.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/ArticlePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/editmode/PreviewEditModePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/editmode/SourceEditModePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/editmode/VisualEditModePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/visualeditor/VisualEditorMenu.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/visualeditor/VisualEditorPageObject.java
src/test/java/com/wikia/webdriver/testcases/mediatests/addvideo/VetArticleCommentsTests.java
src/test/java/com/wikia/webdriver/testcases/mediatests/modal/VetModalCaptionTests.java
src/test/java/com/wikia/webdriver/testcases/mediatests/modal/VetModalWidthTests.java

- Attempt to improve stability of VET tests.
- Few VE related minor fixes
Reviewers:

Ww fixes 2

---

src/test/java/com/wikia/webdriver/elements/oasis/components/templateclassificiation/TemplateClassification.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/SpecialRestorePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/themedesigner/SpecialThemeDesignerPageObject.java

- Improve stability of tests by waiting for element to be clickable before clicking it.

Ww infoboxbuilder fix

---

src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsFollowersResponseTests.java

http://jenkins:8080/job/test-environment-stability-check/35

adding more dependecies

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java

According to the changes:
http://community.wikia.com/wiki/Special:WikiFactory/532/clog
The category has changed and it affected ad unit.

ADEN-3664 Change vertical of avatar wiki

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdDriverForcedStatus.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsAdDriverForcedStatusOasis.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsKruxSegments.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsRoadblocksAfterMultiplePageViewsOasis.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

We're in the process of removing Liftium. We don't need it in tests as well ;)
Connected PRs:
* https://github.com/Wikia/app/pull/11010,
* https://github.com/Wikia/jenkins-jobs/pull/75.

ADEN-3723 Liftium cleanup

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
src/test/java/com/wikia/webdriver/common/dataprovider/mobile/MobileAdsDataProvider.java

Move Krux integration tests to project43

ADEN-3741 Move Krux integration tests to project43

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/chatpageobject/ChatPage.java
src/test/java/com/wikia/webdriver/testcases/chattests/ChatTests.java

[SUS-764](https://wikia-inc.atlassian.net/browse/SUS-764)
I've added new test to check that after typing to long message in chat window a warning will appear. I've also changed css selector assigned to 'chatLoadedIndicator' cause the old one was visible only when there was multiple users in chat room and it didn't seem to work for a test with only one user.
@ludwikkazmierczak @mixth-sense

SUS-764 Add test for too long chat message notification

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/Post.java
src/test/java/com/wikia/webdriver/testcases/discussions/LayoutTests.java

Load more button instead of infinite scroll
https://wikia-inc.atlassian.net/browse/SOC-2352

SOC-2352 | Load more button instead of infinite scroll

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsKruxSegments.java

* use mockAds
* update user kuid

ADEN-3741 Use mockAds in Krux seg tests

---

src/test/java/com/wikia/webdriver/elements/mercury/old/ArticlePageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/ArticlePageTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/curatedcontenttests/MainPageTests.java

@Wikia/x-wing
I'll look if there are more changes needed. Anyway, we have to merge it do master, not earlier and not later than when realising the footer itself.

XW-1581 | fixes due to Design System footer changes

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/globalnav/GlobalNavigation.java
src/test/java/com/wikia/webdriver/testcases/globalnavigationbar/Layout.java

Remove gamestar logo in navbar: https://github.com/Wikia/app/pull/11177
/cc @ludwikkazmierczak @justnpT @nikodamn

ADEN-2756 Remove gamestar logo tests

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java

https://wikia-inc.atlassian.net/browse/SUS-956

Changed following label to watching

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/SearchTests.java

Test was failing because it was trying to test Mercury global nav on Oasis skin (Discussion page) on wiki without Discussions feature. I added annotation to use "dauto" wiki, also created a sample article there.
Reviewers:

Mercury suggestions fix

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/toolbars/CustomizedToolbarComponentObject.java
src/test/java/com/wikia/webdriver/testcases/toolbartests/CustomizeToolbarTests.java

https://wikia-inc.atlassian.net/browse/SUS-957

Sus 957 - changed toolbar label from Follow to Watch

---

gradle/wrapper/gradle-wrapper.properties

Upgrade to gradle 3.0

---

src/test/java/com/wikia/webdriver/testcases/articlepreviewtests/MobilePreviewTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/GoogleFormTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/PolldaddyTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/PollsnackTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/SoundCloudTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/SpotifyTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/TwitterTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/VKTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/WeiboTests.java

QAART-838 Add X-Wing test suite groups

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/SpecialVideosPageObject.java
src/test/java/com/wikia/webdriver/testcases/specialpagestests/VideosPageTests.java

https://wikia-inc.atlassian.net/browse/SUS-756
Removed method that checks sorting dropdown on Special:Videos page as this feature was removed months ago.

Removed method checking not existing feature

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsInterstitialObject.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsInterstitial.java

* Wait for close button
* Wait for interstitial itself (waiting for page load is not always enough)

Aden 3531 interstitial test fix

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/PostEntity.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/PostDetailsPage.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingPostTests.java

* https://wikia-inc.atlassian.net/browse/SOC-2563
Post creator: click on post text area takes user to post details
@justnpT

SOC-2563 | Post creator: click on post text area takes user to post details

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/Post.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/desktop/PostsCreatorDesktop.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/PostsListPage.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/BasePageObject.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingPostTests.java

* https://wikia-inc.atlassian.net/browse/SOC-2560
Post creator: DESKTOP: post creator sticks to the navbar on scroll
@justnpT

SOC-2560 | Post creator: DESKTOP: post creator sticks to the navbar on scroll

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java

Changed CSS selector in data provider (the div IDs are kind of random).

ADEN-3530 fix flite test

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java

ADEN-3530 formatting

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/wam/WamPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/wam/WamTab.java
src/test/java/com/wikia/webdriver/testcases/wampagetests/WamPageTests.java

https://wikia-inc.atlassian.net/browse/SUS-923
* removed test that compares selected tab and header as header is not visible on the page anymore

SUS-923 Removed wam page test for removed feature

---

src/test/java/com/wikia/webdriver/common/core/MailFunctions.java

MailFunctions: improve logging

---

src/test/java/com/wikia/webdriver/common/logging/PageObjectLogging.java

Set mockAds cookie on main domain instead of subdomain

ADEN Set mockAds cookie on correct domain

---

src/test/java/com/wikia/webdriver/common/contentpatterns/TemplateTypes.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/InfoboxBuilderPage.java
src/test/java/com/wikia/webdriver/elements/oasis/components/templateclassificiation/TemplateClassification.java
src/test/java/com/wikia/webdriver/elements/oasis/components/templatecontent/TemplateContent.java
src/test/java/com/wikia/webdriver/elements/oasis/pages/TemplatePage.java
src/test/java/com/wikia/webdriver/testcases/infoboxbuilder/InfoboxBuilderTests.java
src/test/java/com/wikia/webdriver/testcases/templateclassification/TemplateClassificationTest.java

https://wikia-inc.atlassian.net/browse/WW-213

WW-213 create default template for TemplateClassificationTest

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java

Categories for project43.wikia.com has been changed. Code changes below address the changes in our selenium tests.

ADEN-3941 Adjust data provider for project43.wikia.com

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java

Categories for project43.wikia.com has been changed. Below changes fix it in our tests.

ADEN-3941 Adjust data provider to WikiFactory changes

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java

The categories of yugoih.wikia.com has changed. The code changes address them in our tests.

ADEN-3941 Adjust data provider for yugoih.wikia.com

---

src/test/java/com/wikia/webdriver/common/core/elemnt/JavascriptActions.java
src/test/java/com/wikia/webdriver/elements/mercury/old/InteractiveMapsComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/interactivemaps/AddPinComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/interactivemaps/CreateACustomMapComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/interactivemaps/CreateAMapComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/interactivemaps/CreatePinTypesComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/interactivemaps/CreateRealMapComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/interactivemaps/DeleteAMapComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/interactivemaps/EmbedMapComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/interactivemaps/PalantirComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsFandomObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/interactivemaps/InteractiveMapPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/interactivemaps/InteractiveMapsPageObject.java
src/test/java/com/wikia/webdriver/testcases/interactivemapstests/NonSpecificMapTests.java
src/test/java/com/wikia/webdriver/testcases/interactivemapstests/PalantirTests.java
src/test/java/com/wikia/webdriver/testcases/logintests/ForcedLoginTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/InteractiveMapsTests.java

- Added a fix for failing zoom map test
- Some cleanup of a code

Fixed zoom test

---

src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsFollowersMessageTests.java
src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsFollowersResponseTests.java
src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsOwnerTests.java
src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsThreadCreatorTests.java
src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsThreadParticipantTests.java

Split notifications groups into smaller chunks

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsOoyalaObject.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsOoyalaMercury.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsOoyalaOasis.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

Test Ooyala video player with ads on Mercury

ADEN-3902 AdsOoyalaMercury test

---

src/test/java/com/wikia/webdriver/common/contentpatterns/PageContent.java
src/test/java/com/wikia/webdriver/common/core/api/TemplateContent.java
src/test/java/com/wikia/webdriver/testcases/portableinfoboxtests/PortableInfoboxTests.java

Introduce Template content controller

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/HTMLTitleTests.java

Update expected HTML titles for Mercury test due to SEO-498
Reviewers:

Update expected HTML titles

---

src/test/java/com/wikia/webdriver/common/core/url/UrlBuilder.java
src/test/java/com/wikia/webdriver/common/core/video/YoutubeVideo.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/HomePage.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/communitypage/SpecialCommunity.java
src/test/java/com/wikia/webdriver/testcases/communitypagetests/SpecialCommunityPageTests.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

Please do not merge before https://github.com/Wikia/app/pull/11352 is on production

WW-95 go to login page if anon editing disabled tests added

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsTaboolaObject.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsTaboolaOasis.java

* test only containers we control,
* check if loader is requested only when ads are blocked,
* code clean-up.

ADEN-4006 Make Taboola tests more stable

---

src/test/java/com/wikia/webdriver/common/contentpatterns/PageContent.java
src/test/java/com/wikia/webdriver/common/core/elemnt/JavascriptActions.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java

SOC-3134 update to fandom

---

src/test/java/com/wikia/webdriver/common/core/drivers/BrowserAbstract.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsTrackingPixels.java

Fix for AdsTrackingPixels tests
Reviewers:
@ludwikkazmierczak @Wikia/adeng

Change HTTP to HTTPS, disable MITM flag

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/visualeditor/VisualEditorPageObject.java
src/test/java/com/wikia/webdriver/testcases/visualeditor/text/VisualEditorEditingTests.java

(removal of leading space that was not contained in the string to remove).
This fixes the issue by correcting the selection range and including
the space in string to remove.

The VisualEditorEditing_002_delete was failing because of spacing issue

---

src/test/java/com/wikia/webdriver/testcases/discussions/ZeroErrorStateTests.java

SOC-3137 adding RelatedIssues

---

src/test/java/com/wikia/webdriver/testcases/discussions/ZeroErrorStateTests.java

Reverts Wikia/selenium-tests#1502 per @PiotrGackowski request

Revert "SOC-3137 adding RelatedIssues"

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/SpecialVideosPageObject.java
src/test/java/com/wikia/webdriver/testcases/specialpagestests/VideosPageTests.java

Fix VideosPageTest_002 selenium test which is failing because of assertion, test is compering not removed video title with not added video tile

SUS-1185 Fix for VideosPageTest_002 test

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/ArticlePageObject.java
src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleCRUDAnonTests.java
src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleCRUDUserTests.java

@tomasznapieralski 
@kvas-damian

XW-2247 - fix for tests broken by AB test of Add a page button

---

src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleSourceModeTests.java
src/test/java/com/wikia/webdriver/testcases/infoboxbuilder/InfoboxBuilderTests.java

WEST-WING Tag added to InfoboxBuilderTests and TREtests

WW_RelatedIssuesTagAdded

---

src/test/java/com/wikia/webdriver/testcases/discussions/CreatingPostTests.java

I am merging this PR without Code Review because current code have run failure. RelatedIssues were used twice - so there is massive problem.

fixing-compilation-error-for-preview-env

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/visualeditor/VisualEditorPageObject.java
src/test/java/com/wikia/webdriver/testcases/portableinfoboxtests/PortableInfoboxTests.java

fixed failing test
“portableinfoboxtests.PortableInfoboxTests.editInfoboxInVEbyPopup”

WW-427 WW_editInfoboxInVEbyPopup_fixedTtest

---

src/test/java/com/wikia/webdriver/elements/mercury/old/curatedcontent/EditorHomePageObject.java

Items moved one position down due to addition of 'Promote your wiki' on Curated Main Page (http://community.wikia.com/main/edit).

mercury-image-upload-test | fix MercuryImageUploadTest_001_saveNewPhoto

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/RecentWikiActivityTest.java

Related Issues tag is added to failing tests

WW-465_RelatedIssuesAddedToTests

---

src/test/java/com/wikia/webdriver/elements/fandom/components/HeroBlock.java
src/test/java/com/wikia/webdriver/testcases/fandom/HeroUnitTest.java

Check to see if there are five clickable units in the hero mosaic.

Assert that there are five hero units

---

src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleActionsAdminTests.java

adding related issues

---

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsBrowserError.java

Changed page parameters to run test on project43 wiki

Changed page parameters 

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsRecoveryObject.java

Fix ads-recovery-adblock-oasis

ADEN-4226 wait for SP recovery library

---

src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleFeaturesCRUDTestsUser.java
src/test/java/com/wikia/webdriver/testcases/categoriestests/CategoriesArticleTests.java
src/test/java/com/wikia/webdriver/testcases/mediatests/addvideo/VetArticlePlaceholderTests.java
src/test/java/com/wikia/webdriver/testcases/mediatests/modal/VetModalCaptionTests.java

Related issues update

---

src/test/java/com/wikia/webdriver/testcases/discussions/LayoutTests.java

SOC-add-RI Added RI to test

---

src/test/java/com/wikia/webdriver/testcases/visualeditor/VEVideoTests.java
src/test/java/com/wikia/webdriver/testcases/visualeditor/text/VisualEditorEditingTests.java

adding @RelatedIssue to failing tests

related issues

---

src/test/java/com/wikia/webdriver/testcases/signuptests/SignUpTests.java

SOC-deleted-RI-from-test-MAIN-7471

---

src/test/java/com/wikia/webdriver/testcases/discussions/CreatingPostTests.java

SOC-deleted-enebled from test

---

src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleActionsAdminTests.java

WW_RelatedIssues updated in ArticleActionsAdminTests

WW_RelatedIssues updated

---

src/test/java/com/wikia/webdriver/common/contentpatterns/CreateWikiMessages.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/createnewwiki/CreateNewWikiPageObjectStep1.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/createnewwiki/CreateNewWikiPageObjectStep2.java
src/test/java/com/wikia/webdriver/testcases/createawikitests/CreateWikiTests_lang.java
src/test/java/com/wikia/webdriver/testcases/createawikitests/CreateWikiTests_loggedInUser.java
src/test/java/com/wikia/webdriver/testcases/createawikitests/CreateWikiTests_loggedOutUser.java

Preview to master 23.11

---

src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/GuidelinesPage.java
src/test/java/com/wikia/webdriver/testcases/discussions/GuidelinesTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/LayoutTests.java

Soc turn off test

---

src/test/java/com/wikia/webdriver/common/contentpatterns/PageContent.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorReviewChangesDialog.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/ArticlePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/visualeditor/VisualEditorPageObject.java
src/test/java/com/wikia/webdriver/testcases/visualeditor/VEImageTests.java
src/test/java/com/wikia/webdriver/testcases/visualeditor/text/VisualEditorEditingTests.java

https://wikia-inc.atlassian.net/browse/XW-2345
@Wikia/x-wing @petrosinka

XW-2345 | fixes due to Visual Editor X-Wing changes

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/SearchTests.java

With new Search in development, let's disable the faulty tests related to current legacy feature
https://wikia-inc.atlassian.net/browse/SUS-1151

SUS-1151: disable faulty mercury search tests

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/SearchTests.java

Reverts Wikia/selenium-tests#1591

Revert "SUS-1151: disable faulty mercury search tests"

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/CategoryPageTest.java

WW-604_RelatedIssues tag added

WW-604_RelatedIssues tag added

---

src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleCRUDAnonTests.java
src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleFeaturesCRUDTestsUser.java
src/test/java/com/wikia/webdriver/testcases/categoriestests/CategoriesArticleTests.java
src/test/java/com/wikia/webdriver/testcases/globalshortcuts/ActionExplorerTest.java
src/test/java/com/wikia/webdriver/testcases/infoboxbuilder/InfoboxBuilderTests.java
src/test/java/com/wikia/webdriver/testcases/mediatests/addvideo/VetArticlePlaceholderTests.java

added/removed RelatedIssues tags

WW RelatedIssuesUpdate

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/IntroducingFollowingModal.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/MoreOptionsPopOver.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/Post.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/ShareDialog.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/desktop/SortingFiltersOnDesktop.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/PostsListPage.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/LayoutTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/NavigatingTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/PromotingTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/SharingTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/SortingTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/UpvotingTests.java

https://wikia-inc.atlassian.net/browse/SOC-3665
Align automated test to following

SOC-3665 | align automated test to following

---

src/test/java/com/wikia/webdriver/elements/mercury/pages/CategoryPage.java

SEO-577: Mercury - update tests for category page without members

---

src/test/java/com/wikia/webdriver/testcases/discussions/ZeroErrorStateTests.java

SOC-3667 Add RI and Enabled

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/SearchTests.java

- https://wikia-inc.atlassian.net/browse/SOC-3682

SOC-3682 | fix: update sustaining test to click following modal

---

readme.md

Reviewers:
@ludwikkazmierczak @PiotrGackowski

QAART-887 Update readme

---

src/test/java/com/wikia/webdriver/testcases/chattests/ChatTests.java

[SUS-1377](https://wikia-inc.atlassian.net/browse/SUS-1377)

SUS-1377 Fix randomly failing Chat tests

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorAddMediaDialog.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/visualeditor/VisualEditorPageObject.java
src/test/java/com/wikia/webdriver/testcases/infoboxbuilder/InfoboxBuilderTests.java
src/test/java/com/wikia/webdriver/testcases/infoboxbuilder/Sidebar.java
src/test/java/com/wikia/webdriver/testcases/visualeditor/VEImageTests.java
src/test/java/com/wikia/webdriver/testcases/visualeditor/VEVideoTests.java

https://wikia-inc.atlassian.net/browse/XW-2449

XW-2449 | Fix VE video and image tests

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/Replies.java
src/test/java/com/wikia/webdriver/testcases/discussions/LockingPostTests.java

Desktop locking tests stabilization
@tortila

SOC | Desktop locking tests stabilization

---

src/test/java/com/wikia/webdriver/testcases/discussions/FollowingPostTests.java

Test for following on following tab timeouts because of huge amount of posts. Pagination will be introduced in SOC-3674.
@tortila

SOC | turn off test because of timeout

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/BaseReplyCreator.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/PostActionsRow.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/ReplyCreator.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/desktop/ReplyCreatorDesktop.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/mobile/ReplyCreatorMobile.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/PostDetailsPage.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingReplyTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/FollowingPostTests.java

* https://wikia-inc.atlassian.net/browse/SOC-2377
* https://wikia-inc.atlassian.net/browse/SOC-2556
* https://wikia-inc.atlassian.net/browse/SOC-3228
Reply creator: DESKTOP: editor active for logged in uses
Reply creator: Add reply
As Engineer I'd like to have automated tests cases for creating reply with following post
@tortila

SOC-2377 SOC-2556 SOC-3228 | Add reply under post tests.

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/PostEntity.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/PostsListPage.java
src/test/java/com/wikia/webdriver/testcases/discussions/CategoriesTests.java

Categories tests stabilization
@tortila

SOC | fix: categories tests stabilization

---

src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/PostsListPage.java

categories tests stabilization
@tortila

SOC | categories tests stabilization

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/ad/FandomVideoFanTakeover.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/ad/VideoFanTakeover.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsVuapFandom.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsVuapOasis.java

- adding new selectors after veep refactor on oasis and mercury

ADEN-4462 Adjust Vuap tests to code refactor

---

src/test/java/com/wikia/webdriver/common/remote/operations/http/BaseRemoteOperation.java

Ticket: https://wikia-inc.atlassian.net/browse/SOC-3861
This should fix most of the selenium tests failures on jenkins

SOC-3861 fix invalid permissions for tests

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/HTMLTitleTests.java

Remove obsolete /main/section test case

---

src/test/java/com/wikia/webdriver/testcases/adstests/TestIVWAnalyticsProvider.java

##Links
https://wikia-inc.atlassian.net/browse/ADEN-4531
##Description
Investigate why ads-test-ivw-de is randomly failing

ADEN-4531 | Investigate why ads-test-ivw-de is randomly failing

---

src/test/java/com/wikia/webdriver/testcases/contentreview/ContentReviewTests.java

https://wikia-inc.atlassian.net/browse/XW-2682
//cc @Wikia/x-wing @ludwikkazmierczak

XW-2682 | running content review tests on default wiki

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/ad/AutoplayVuap.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsVuapOasisAutoplay.java

https://wikia-inc.atlassian.net/browse/ADEN-4609
Remove vuapAutoplayShouldCloseWhenClickingCloseButton test

ADEN-4609 | Remove vuapAutoplayShouldCloseWhenClickingCloseButton test	

---

src/test/java/com/wikia/webdriver/testcases/contentreview/ContentReviewTests.java

fixing error with content review tests

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsTrackingPixels.java

remove not used tracking pixel tests

ADEN | chore: remove not used tracking pixel tests

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/Post.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/PostEntity.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/PostsListPage.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/BasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/signup/UserProfilePageObject.java
src/test/java/com/wikia/webdriver/testcases/discussions/ReportingPostTests.java

https://wikia-inc.atlassian.net/browse/SOC-3836

SOC-3836 Fix failing tests for reporting posts

---

src/test/java/com/wikia/webdriver/elements/fandom/FandomPage.java
src/test/java/com/wikia/webdriver/elements/fandom/components/FanFeed.java
src/test/java/com/wikia/webdriver/elements/fandom/components/LoadMore.java
src/test/java/com/wikia/webdriver/elements/fandom/components/WPLoginBox.java
src/test/java/com/wikia/webdriver/elements/fandom/components/WPNotifications.java
src/test/java/com/wikia/webdriver/elements/fandom/pages/HomePage.java
src/test/java/com/wikia/webdriver/testcases/fandom/FanFeedTest.java

Adding two tests: 
* Is the fan feed displayed
* Is the load more button working with CORS
Fixed one test: 
* Feature image required

Fan 1381 Testing load more button on home page

---

src/test/java/com/wikia/webdriver/common/contentpatterns/MercuryWikis.java
src/test/java/com/wikia/webdriver/testcases/discussions/ZeroErrorStateTests.java

Ticket: https://wikia-inc.atlassian.net/browse/SOC-3829
Fixes tests for zero error state

SOC-3829 | added new wiki with empty discussions

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/HTMLTitleTests.java

https://wikia-inc.atlassian.net/browse/XW-2650
Tests are passing with the code recently merged to dev.
http://jenkins.wikia-prod:8080/view/X-Wing/view/mercury-sandbox/job/xwing-mercury-htmlTitleSet-sandbox/14/

XW-2650 | Update case that checks {{DISPLAYTITLE}} support

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/messagewall/MessageWall.java
src/test/java/com/wikia/webdriver/testcases/messagewall/MessageWallTests.java

SOC-1559 Remove RI and add CB

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorSourceEditorDialog.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/visualeditor/VisualEditorPageObject.java
src/test/java/com/wikia/webdriver/testcases/visualeditor/text/VisualEditorEditingTests.java

* https://wikia-inc.atlassian.net/browse/XW-2689
* https://github.com/Wikia/app/pull/12369
* https://github.com/Wikia/selenium-tests/pull/1589
Revert changes introduced in https://github.com/Wikia/selenium-tests/pull/1589 and fix whatever broke.
This should also stabilize the tests that were failing for a long time:
* xwing-app-veediting - [passed on sandbox](http://jenkins.wikia-prod:8080/view/X-Wing/view/sandbox/job/xwing-app-veediting-sandbox/12/)
* xwing-app-vedeleting - [passed on sandbox](http://jenkins.wikia-prod:8080/view/X-Wing/view/sandbox/job/xwing-app-vedeleting-sandbox/13/)
@Wikia/x-wing @qaga

XW-2689 | Fix VE tests after hack removal

---

src/test/java/com/wikia/webdriver/common/contentpatterns/MercuryWikis.java
src/test/java/com/wikia/webdriver/common/remote/Discussions.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/desktop/Promoting.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/BasePageObject.java
src/test/java/com/wikia/webdriver/testcases/discussions/CategoriesTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/DeleteAllPostsByUserTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/PromotingTests.java

[Ticket](https://wikia-inc.atlassian.net/browse/IRIS-3830)

IRIS-3830 | cleaned up tests and page objects, added new test cases for mobile view

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/search/crosswikisearch/CrossWikiSearchPageObject.java

SUS-Selenium-pan002 Added new log

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/SpecialWikiActivityPageObject.java
src/test/java/com/wikia/webdriver/testcases/messagewall/MessageWallTests.java

https://wikia-inc.atlassian.net/browse/SUS-1309

SUS-1309: Introduce regression test to verify title, author, content of Wall Thread shows properly in Wiki Activity

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/messagewall/MessageWall.java
src/test/java/com/wikia/webdriver/testcases/messagewall/MessageWallTests.java

Couldn't reproduce original issue, but fixed one with empty msg body

Qaart 937 not logged in user

---

src/test/java/com/wikia/webdriver/common/properties/Credentials.java
src/test/java/com/wikia/webdriver/common/templates/fandom/FandomTestTemplate.java
src/test/java/com/wikia/webdriver/elements/fandom/FandomPage.java

Related PRs:
https://github.com/Wikia/upstream/pull/1078
https://github.com/Wikia/selenium-config/pull/45

FAN-1658 sandbox-qa instead of qa

---

src/test/java/com/wikia/webdriver/testcases/visualeditor/text/VisualEditorEditingTests.java

* Remove VisualEditorDelete group
* Move test 002 from VisualEditorDelete to VisualEditorEditing group
Reviewer:
@qaga

QAART-943 Clean up X-Wing app test suite

---

src/test/java/com/wikia/webdriver/testcases/visualeditor/VEImageTests.java

fix for VE image allignment test

---

src/test/java/com/wikia/webdriver/testcases/visualeditor/text/VisualEditorEditingTests.java

Remove unused import

---

src/test/java/com/wikia/webdriver/testcases/adstests/TestIVWAnalyticsProvider.java

https://wikia-inc.atlassian.net/browse/ADEN-4782
Disable ivw tests

ADEN-4782 | disable ivw tests

---

src/test/java/com/wikia/webdriver/common/core/helpers/Emulator.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/ad/VideoFanTakeover.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsVuapMercury.java

https://wikia-inc.atlassian.net/browse/ADEN-4804
ads-vuap-mercury tests stabilization

ADEN-4804 | ads-vuap-mercury tests stabilization

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/BaseReplyCreator.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/desktop/ReplyCreatorDesktop.java

jenkins execution: http://jenkins.wikia-prod:8080/view/Iris/view/preview/job/iris-discussions-creating-replies-desktop-preview/4/artifact/logs/log.html

IRIS-hotfix | fixes for failing tests for adding a reply in discussions post

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/BaseReplyCreator.java
src/test/java/com/wikia/webdriver/testcases/logintests/LoginTests.java

fixes a test that shouldn't have passed, ever. Also adds explicit wait

IRIS-hotfix-2

---

src/test/java/com/wikia/webdriver/common/core/Helios.java
src/test/java/com/wikia/webdriver/common/remote/operations/http/BaseRemoteOperation.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/category/CategoriesFieldset.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/PostsListPage.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingReplyTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/LayoutTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/SharingTests.java

IRIS-hotfix | fixes a bunch of tests that were failing, mainly due to moving them from dauto to other wikis

---

src/test/java/com/wikia/webdriver/testcases/discussions/CategoriesTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingReplyTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/EditingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/FollowingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/GuidelinesTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/LayoutTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/LockingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/NavigatingTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/ReportingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/SharingTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/SortingTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/UpvotingTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/ZeroErrorStateTests.java

IRIS-refactor | use global settings for browser resolution

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/global_navitagtion/NotificationsComponentObject.java

Use more specific CSS selector to get bubblesCount for Wall, not for on site notifications

NotificationsComponentObject: fix verifyNotification

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/global_navitagtion/NotificationsComponentObject.java

Porting @macbre fixes to preview

Wall notifications fix

---

src/test/java/com/wikia/webdriver/testcases/mediatests/suggestions/VideoSuggestionsTests.java

Test stopped working after New Local Nav was introduced. Replaced edit button clicking action with just "go to edit mode by url param"

Video Suggestions Test Update

---

src/test/java/com/wikia/webdriver/testcases/notificationstests/messagewallnotifications/MessageWallNotificationsFollowersResponseTests.java

fixed test dependencies

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/ApesterWidgetPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/GoogleFormWidgetPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/PlaybuzzWidgetPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/PolldaddyWidgetPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/PollsnackWidgetPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/SoundCloudWidgetPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/SpotifyWidgetPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/TwitterWidgetPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/VKWidgetPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/WeiboWidgetPageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/WidgetPageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/widgettests/AllTagsTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/widgettests/ApesterTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/widgettests/PlaybuzzTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/AllTagsTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/ApesterTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/PlaybuzzTests.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

merging to preview changes from https://github.com/Wikia/selenium-tests/pull/1743
@nikodamn 
@qaga 
@Wikia/x-wing

XW-3089: Apester and Playbuzz widget tests to preview

---

config_default.yml

Change default browser in config file to CHROME

---

src/test/java/com/wikia/webdriver/elements/mercury/components/Search.java

Ticket to be created to solve this issue ultimately

Change in expected error message

---

src/test/java/com/wikia/webdriver/common/logging/PageObjectLogging.java
src/test/java/com/wikia/webdriver/testcases/commentstests/BlogCommentsTests.java
src/test/java/com/wikia/webdriver/testcases/notificationstests/ForumNotificationsTests.java

Reverts Wikia/selenium-tests#1706

Revert "SUS-1737: In Wall and Comments tests double-check that user is logged in"

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/HomePage.java
src/test/java/com/wikia/webdriver/testcases/globalshortcuts/ActionExplorerTest.java

https://wikia-inc.atlassian.net/browse/XW-3243
Ping @ludwikkazmierczak @rogatty @qaga

XW-3243 | Wait for GlobalShortcuts

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/globalnav/GlobalNavigation.java

[Ticket](https://wikia-inc.atlassian.net/browse/IRIS-4305)

IRIS-4305 | fix logOut method after href is changed to button

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsRecoveryObject.java

https://wikia-inc.atlassian.net/browse/ADEN-5041

ADEN-5041 uncomment PageFair adonis checks

---

src/test/java/com/wikia/webdriver/common/core/helpers/User.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/messagewall/MessageWall.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/messagewall/MessageWallThreadPageObject.java
src/test/java/com/wikia/webdriver/testcases/messagewall/MessageWallTests.java

Summary of changes:
- added a test case to cover bug reported as P2: https://wikia-inc.atlassian.net/browse/IRIS-4338
- changed selector to distinguish thread list and thread details view
- added missing group for one test

IRIS-4352 | Discussion redirects causes 500 on some Board Thread pages

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsOoyalaObject.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsOoyalaMercury.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsPremiumPrerollOasis.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

https://wikia-inc.atlassian.net/browse/ADEN-5099

ADEN-5099 tests for premium video preroll @oasis

---

src/test/java/com/wikia/webdriver/common/core/helpers/User.java
src/test/java/com/wikia/webdriver/elements/mercury/old/curatedcontent/CuratedContentPageObject.java
src/test/java/com/wikia/webdriver/elements/mercury/old/curatedcontent/CuratedEditorFormPageObject.java
src/test/java/com/wikia/webdriver/elements/mercury/old/curatedcontent/CuratedMainPagePageObject.java
src/test/java/com/wikia/webdriver/elements/mercury/old/curatedcontent/EditorHomePageObject.java
src/test/java/com/wikia/webdriver/elements/mercury/old/curatedcontent/curatededitorform/CategoryFormPageObject.java
src/test/java/com/wikia/webdriver/elements/mercury/old/curatedcontent/curatededitorform/ItemFormPageObject.java
src/test/java/com/wikia/webdriver/elements/mercury/old/curatedcontent/curatededitorform/SectionFormPageObject.java
src/test/java/com/wikia/webdriver/elements/mercury/old/curatedcontent/curatededitorform/SectionItemListPageObject.java
src/test/java/com/wikia/webdriver/elements/mercury/old/curatedcontent/imageupload/CroppingToolPageObject.java
src/test/java/com/wikia/webdriver/elements/mercury/old/curatedcontent/imageupload/SearchForImagePageObject.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/ArticlePage.java
src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleFeaturesCRUDTestsUser.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/curatedcontenttests/CropImageTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/curatedcontenttests/EditorTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/curatedcontenttests/ImageUploadTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/curatedcontenttests/MainPageTests.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/curatedcontenttests/NavigationTests.java

Initial refactor

---

src/test/java/com/wikia/webdriver/common/core/helpers/User.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/globalnav/GlobalNavigation.java
src/test/java/com/wikia/webdriver/testcases/globalnavigationbar/Layout.java
src/test/java/com/wikia/webdriver/testcases/globalnavigationbar/Navigating.java
src/test/java/com/wikia/webdriver/testcases/globalnavigationbar/Searching.java

https://wikia-inc.atlassian.net/browse/XW-3402
* Fixing existing global nav tests
* removing outdated ones
* adding new test cases
@ludwikkazmierczak @Wikia/x-wing

XW-3402 | Fixing/adding tests for global nav on Oasis skin

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/globalnav/GlobalNavigation.java
src/test/java/com/wikia/webdriver/testcases/globalnavigationbar/Layout.java

https://github.com/Wikia/selenium-tests/pull/1798
https://wikia-inc.atlassian.net/browse/XW-3402
@Wikia/x-wing

XW-3402 | Testing partner slot for de lang in global navigation bar

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsOoyalaObject.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsPremiumPrerollMercury.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

https://wikia-inc.atlassian.net/browse/ADEN-5197

ADEN-5197 | Tests for Mercury premium ooyala preroll

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/GoogleFormWidgetPageObject.java
src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleFeaturesCRUDTestsUser.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/widgettests/GoogleFormTests.java

Hacks Hacks hacks

---

src/test/java/com/wikia/webdriver/common/core/annotations/InBrowser.java
src/test/java/com/wikia/webdriver/common/core/configuration/Configuration.java
src/test/java/com/wikia/webdriver/common/core/drivers/browsers/ChromeBrowser.java
src/test/java/com/wikia/webdriver/common/core/helpers/Emulator.java
src/test/java/com/wikia/webdriver/common/logging/PageObjectLogging.java
src/test/java/com/wikia/webdriver/common/templates/core/CoreTestTemplate.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/BasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/globalnav/GlobalNavigation.java
src/test/java/com/wikia/webdriver/testcases/globalnavigationbar/Layout.java
src/test/resources/ChromeProfiles/default/Default/Extensions#aapocclcgogkmnckokdopfmhonfmgoek/0.9_0/_locales/cs/messages.json

Patching preview with fixes merged to master

Layout testing on chrome

---

src/test/java/com/wikia/webdriver/common/contentpatterns/PageContent.java

Fix test failure caused by rebrand.

SUS-2197: "A Fandom User" => "A FANDOM User"

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java
src/test/java/com/wikia/webdriver/testcases/visualeditor/VEImageTests.java

@Wikia/x-wing 
@ludwikkazmierczak 
@nikodamn

XW-2761 | test fixes

---

src/test/java/com/wikia/webdriver/common/core/Helios.java

Added internal header to Helios INFO calls

Added internal header to Helios INFO calls

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/old/widgettests/ApesterTests.java

* Prepare Mercury Article tests to staging env - tests should prepare data set on it's own, before test's execution.
* Tests verified working on production
@ludwikkazmierczak @sczerwinski-wikia

Staging apester widget mercury

---

src/test/java/com/wikia/webdriver/testcases/widgettests/ApesterTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/PlaybuzzTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/PolldaddyTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/PollsnackTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/SoundCloudTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/SpotifyTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/TwitterTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/VKTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/WeiboTests.java

Prepare all tests for app widgets for migrating to staging env
@sczerwinski-wikia

App widgets staging

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/old/widgettests/ApesterTests.java
src/test/java/com/wikia/webdriver/testcases/widgettests/PollsnackTests.java

Fix:
* Pollsnack-app test
* Apester-mercury test

Fix pollsnack app widget tests

---

src/test/java/com/wikia/webdriver/common/core/elemnt/JavascriptActions.java
src/test/java/com/wikia/webdriver/common/core/helpers/Emulator.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/ArticlePage.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationMercuryTests.java

ticket: XW-3696 (no link here because Jira down)
@Wikia/x-wing

XW-3696 | fix scroll position detection in Mercury Navigation tests

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java

wait for evelemt present, not visible

ADEN-5521 Fix ads-mercury-vuap

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/vet/VetAddVideoComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/messagewall/MessageWall.java
src/test/java/com/wikia/webdriver/testcases/mediatests/VetAddingVideoTests.java

Run every test 20 times:
http://jenkins.wikia-prod:8080/job/seleniumTestBuild_new/14/artifact/logs/log.html

VetAddingVideoTests fixes

---

src/test/java/com/wikia/webdriver/elements/mercury/old/CommentsPageObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/old/CommentsTests.java

Fixed stale element reference and "other element would receive a click"
http://jenkins.wikia-prod:8080/job/seleniumTestBuild_new/20/artifact/logs/log.html

Sustaining mercury tests fix

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/mobile/DiscussionsHeader.java

Tests passed: http://jenkins.wikia-prod:8080/view/Iris/view/preview/job/iris-discussions-sorting-preview/190/

IRIS-hotfix | change filter selector for sorting tests

---

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsPremiumPrerollMercury.java

ADEN-5549 | use control group for MOBILE_FEATURED_VIDEO_AUTOPLAY ABTest

---

src/test/java/com/wikia/webdriver/common/core/helpers/Emulator.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/UserPostsPage.java
src/test/java/com/wikia/webdriver/testcases/discussions/DeleteAllPostsByUserTests.java

[Ticket](https://wikia-inc.atlassian.net/browse/IRIS-4724)
At this point, where mobile and desktop functionality are that different, I think it's reasonable to refactor the tests to use 2 different class for mobile and desktop. Here is [a ticket](https://wikia-inc.atlassian.net/browse/IRIS-4732) to follow up.

IRIS-4724 | Fix tests for deleting all posts by user

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/DiscussionsConstants.java
src/test/java/com/wikia/webdriver/testcases/discussions/CategoriesTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingReplyTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/DeleteAllPostsByUserTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/EditingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/FollowingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/GuidelinesTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/LayoutTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/LockingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/NavigatingTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/PromotingTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/ReportingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/SharingTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/SortingTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/UpvotingTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/ZeroErrorStateTests.java

The same change in many places. Context in slack channel `#quality-management`

IRIS-4724 fix: change deprecated browserSize to use Emulator

---

src/test/java/com/wikia/webdriver/elements/oasis/CommunityHeader.java
src/test/java/com/wikia/webdriver/testcases/communityheadertests/CommunityHeaderTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/CommunityHeaderTests.java

https://wikia-inc.atlassian.net/browse/XW-3738
@Wikia/x-wing

XW-3738 | community header tests on discussions

---

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsVuapFandom.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

Connected PR: https://github.com/Wikia/jenkins-jobs/pull/297

ADEN-5628 Moved time progressing test to a new group

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/ad/AutoplayVuap.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/ad/VuapAssertions.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsVuapOasis.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsVuapResolvedState.java

https://wikia-inc.atlassian.net/browse/ADEN-5649
@Wikia/adeng

ADEN-5649 | Make VUAP Oasis tests more stable

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsOoyalaObject.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsPremiumPrerollMOATTracking.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsPremiumPrerollMercury.java

https://wikia-inc.atlassian.net/browse/XW-3750
@Wikia/x-wing @Wikia/adeng

XW-3750 | fix FV preroll mobile test

---

src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleSourceModeTests.java

Changed the name of used image so that the name of the one from staging is used on preview as well.

Changed name of the image to be consistent across environments

---

src/test/java/com/wikia/webdriver/elements/oasis/components/notifications/Notification.java
src/test/java/com/wikia/webdriver/elements/oasis/components/notifications/NotificationType.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java

Adjustment of selenium tests for new version of Banner Notifications

XW-bannerNotif

---

src/test/java/com/wikia/webdriver/common/core/Assertion.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/toolbars/CustomizedToolbarComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/forumpageobject/ForumManageBoardsPageObject.java

Last thing to fix notifications in Sus tests

Notifications fix

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/SmartBannerTest.java

Change was made so the test is working on staging

XW-2497 changed wiki where test is executed

---

src/test/java/com/wikia/webdriver/elements/mercury/components/TopBar.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationMercuryTests.java

Managed to replicate it in:
http://jenkins.wikia-prod:8080/job/seleniumTestBuild_new/64/
Fixed in:
http://jenkins.wikia-prod:8080/job/seleniumTestBuild_new/66/

Qaart 1042

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/createnewwiki/CreateNewWikiPageObjectStep2.java

Running test using this branch completes successfully on preview
http://jenkins.wikia-prod:8080/view/Sustaining/view/Sustaining-preview/job/sustaining-app-CNW-user-preview/385/

Fix dropdown error

---

src/test/java/com/wikia/webdriver/elements/mercury/old/LightboxComponentObject.java

Seems like we must scroll to the image first or else we cannot click it.

Fix Mercury lightbox test

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/BasePostsCreator.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/BaseReplyCreator.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/Post.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/PostEntity.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/PostsCreator.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/Reply.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/ReplyCreator.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/desktop/PostsCreatorDesktop.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/desktop/ReplyCreatorDesktop.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/mobile/PostsCreatorMobile.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/mobile/ReplyCreatorMobile.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/BasePageObject.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingReplyTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/OpenGraphTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/OpengraphTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/UploadingImageTests.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

[Ticket](https://wikia-inc.atlassian.net/browse/IRIS-4896)

IRIS-4896 | Implement automated tests for OpenGraph in Discussions

---

src/test/java/com/wikia/webdriver/common/contentpatterns/AdsFandomContent.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/ad/AutoplayVuap.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/ad/VideoFanTakeover.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/mcfooter/MixedContentFooter.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsFandomObject.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsVuapFandom.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsVuapMercury.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsVuapOasis.java

Revert of @gabrys changes and fixes for `ads-app-vuap-resolved-oasis`.

ADEN-5954 Fix ads-app-vuap-resolved-oasis job

---

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsBtfBlocking.java

Let's not use provider that doesn't exist

ADEN-mercury-btf-dataprovider

---

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsFandomOoyala.java

We updated selectors for Fandom video.
@Wikia/adeng

Update selectors for fandom video

---

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsFandomOoyala.java

/ping @Wikia/adeng for keeping you in the loop

FAN-2904 | Remove smart banner

---

src/test/java/com/wikia/webdriver/common/core/configuration/EnvType.java
src/test/java/com/wikia/webdriver/common/core/url/UrlBuilder.java
src/test/java/com/wikia/webdriver/common/templates/NewTestTemplate.java

dev: http://www.sczerwinski.wikia-dev.pl/WAM
preview (newStagingUrlFormat=false): http://preview.www.wikia.com/WAM
preview (newStagingUrlFormat=true): http://www.preview.wikia.com/WAM
staging: http://www.wikia-staging.com/WAM
prod: http://www.wikia.com/WAM

Handle www.wikia.com on staging environments

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/dpl/DplQueryTestPageObject.java
src/test/java/com/wikia/webdriver/testcases/dpl/DplQueryTest.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

Create simple test to verify the result set of some DPL queries.
Due to the nature of DPL, some wiki pages had to be created - http://sustainingtest.wikia.com/wiki/DplQueryTest
https://wikia-inc.atlassian.net/browse/SUS-3265

SUS-3265 create simple test case for DPL

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/SpecialNewPages.java
src/test/java/com/wikia/webdriver/testcases/specialpagestests/NewPagesTests.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

Add simple test that creates new article and verifies it shows up on Special:NewPages page
https://wikia-inc.atlassian.net/browse/SUS-3492

SUS-3492 Selenium test for Special:NewPages

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/category/CategoriesFieldset.java
src/test/java/com/wikia/webdriver/testcases/discussions/CategoriesTests.java

https://wikia-inc.atlassian.net/browse/IRIS-5187
@Wikia/iris

IRIS-5187 | Add test for reordering discussions categories

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/BasePostsCreator.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/BaseReplyCreator.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/Post.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/PostsCreator.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/Replies.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/desktop/PostsCreatorDesktop.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/mobile/PostsCreatorMobile.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/CreatingReplyTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/LockingPostTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/OpenGraphTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/UploadingImageTests.java

https://wikia-inc.atlassian.net/browse/IRIS-5119

IRIS-5119 | Add test cases for posts without text

---

src/test/java/com/wikia/webdriver/elements/common/CommunityHeader.java
src/test/java/com/wikia/webdriver/elements/oasis/components/globalshortcuts/ActionExplorerModal.java
src/test/java/com/wikia/webdriver/elements/oasis/components/globalshortcuts/KeyboardShortcutsModal.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/modalwindows/AddMediaModalComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/modalwindows/CreateArticleModalComponentObject.java
src/test/java/com/wikia/webdriver/testcases/communityheadertests/CommunityHeaderTests.java

https://wikia-inc.atlassian.net/browse/XW-4317
@Wikia/x-wing

XW-4317 | tests for new shortcuts in Community Header

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/PlaybuzzWidgetPageObject.java

Playbuzz Widget new selectors updated

---

src/test/java/com/wikia/webdriver/common/core/url/FandomUrlBuilder.java
src/test/java/com/wikia/webdriver/common/core/url/UrlBuilder.java

Use env as actual environment and envType as type of the environment.

Differentiate env type from actual env in UrlBuilder

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/SpecialNewFilesPage.java

...as wait-forElementClickable doesn't handle the case

Other-element-would-reveive-a-click error fix

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/SpecialNewFilesPage.java
src/test/java/com/wikia/webdriver/testcases/imageservingtests/ImageStorageTests.java

fixed deleteImage test and removed outdated relatedIssue

XW-image storage

---

src/test/java/com/wikia/webdriver/testcases/activityfeedstests/WikiActivityTests.java

https://wikia-inc.atlassian.net/browse/IRIS-5502
@Wikia/iris

IRIS-5502 | Mark articleEditWithoutVisualChangeIsNotRecordedInWikiActivity as broken

---

src/test/java/com/wikia/webdriver/common/contentpatterns/AdsContent.java

https://wikia-inc.atlassian.net/browse/XW-4155
@Wikia/x-wing
@Wikia/adeng

XW-4155 | fix recirculation-prefooter selector

---

src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationMercuryTests.java

@tortila @ludwikkazmierczak @sczerwinski-wikia

Remove deprecated related issue annotation

---

src/test/java/com/wikia/webdriver/elements/mercury/components/Navigation.java

Due to X-Wing changes: https://github.com/Wikia/mobile-wiki/commit/8621b0556c78b812843bb5031bb0fd27fa96e8fe#diff-d4f85616f7adbd998608ca23d8b27948L19

Update CSS selector for nav login on Mobile

---

src/test/java/com/wikia/webdriver/elements/mercury/old/ArticlePageObject.java
src/test/java/com/wikia/webdriver/elements/mercury/old/PortableInfoboxObject.java
src/test/java/com/wikia/webdriver/testcases/mercurytests/PortableInfoboxTests.java

https://wikia-inc.atlassian.net/browse/XW-4780
@Wikia/x-wing 
Old PR:
https://github.com/Wikia/selenium-tests/pull/2212

XW-4780 | Fixed failing tests.

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/desktop/PostsCreatorDesktop.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/desktop/ReplyCreatorDesktop.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/mobile/PostsCreatorMobile.java
src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/mobile/ReplyCreatorMobile.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/GuidelinesPage.java

During Lightweight Contributions feature release we changes some editors (inline, standalone etc.) selectors. This PR updates them.
@Wikia/iris @chessky @tortila

Discussion editors selectors update after Lightweight Contributions release

---

config_default.yml
src/test/java/com/wikia/webdriver/common/core/configuration/Configuration.java

Captchapath is not used at the moment (619a5d4e16114baedfecca71ae861e91880048a5), hence I didn't create a const for a captcha.txt filename
http://jenkins.wikia-prod:8080/job/seleniumTestBuild_new/162/

Use seleniumConfigPath instead of credentialsPath

---

src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/GuidelinesPage.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/PostsListPage.java
src/test/java/com/wikia/webdriver/testcases/discussions/DiscussionsCreation.java

IRIS-5781 Add test for guidelines default text for newly created Discussions page.
@Wikia/iris

IRIS-5781 Guidelines default text for newly created Discussions page

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/BaseReplyCreator.java
src/test/java/com/wikia/webdriver/testcases/discussions/PollsTests.java
src/test/java/com/wikia/webdriver/testcases/discussions/UploadingImageTests.java

Fix image upload test on Discussion

---

src/test/java/com/wikia/webdriver/elements/mercury/components/Navigation.java

Update user avatar on mobile CSS selector

---

src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/GuidelinesPage.java

Update guidelines editor text area

---

src/test/java/com/wikia/webdriver/testcases/social/MercuryAssetCheck.java

The fewer "real" wikis in our tests the better.

Get rid of Glee wiki

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/modalwindows/FacebookSignupModalComponentObject.java
src/test/java/com/wikia/webdriver/testcases/auth/FacebookTests.java

Due to update of Facebook's registration auth page - fix broken fb registration test
@Wikia/iris @chessky @ludwikkazmierczak

IRIS-4714 Fix FB auth test

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/modalwindows/FacebookSignupModalComponentObject.java
src/test/java/com/wikia/webdriver/testcases/auth/FacebookTests.java

Remove password from FB auth tests
@Wikia/iris

IRIS-5834 Remove password from FB auth tests

---

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/Poll.java
src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/PostDetailsPage.java
src/test/java/com/wikia/webdriver/testcases/discussions/PollsTests.java

@Wikia/iris @ludwikkazmierczak @sczerwinski-wikia @chessky

Add tests for voters list in polls

---

src/test/java/com/wikia/webdriver/common/core/api/ArticleContent.java
src/test/java/com/wikia/webdriver/common/core/api/CuratedContent.java
src/test/java/com/wikia/webdriver/common/core/api/DeleteMWVideo.java
src/test/java/com/wikia/webdriver/common/core/api/EditToken.java
src/test/java/com/wikia/webdriver/common/core/api/ForumBoardContent.java
src/test/java/com/wikia/webdriver/common/core/url/BaseUrlBuilder.java

http://jenkins.wikia-prod:8080/view/Core%20Platform/view/HTTPS%20tests/view/groups/job/sustaining-app-weiboWidget-https/78/artifact/logs/log.html

Handshake failure fix for, among the others, Weibo tests

---

src/test/java/com/wikia/webdriver/common/logging/Log.java

Stop saving HTML that no one uses. It takes 5mb per file for each build

no more HTML saving! It's so 80s

---

src/test/java/com/wikia/webdriver/common/core/url/UrlBuilder.java
src/test/java/com/wikia/webdriver/testcases/adstests/TestVideoVelesMobile.java

Fix missing query string http://jenkins.wikia-prod:8080/view/Ads/view/ads-mobile-wiki-preview_tmp_1531315726090_ryba-v3/job/ads-mobile-wiki-amazon-preview_1531315726090/ws/logs/log.html

Add query string if specified

---

src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

Update testsuite after removed class

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/toolbars/CustomizedToolbarComponentObject.java

Move the wait before the assertion to avoid races
https://wikia-inc.atlassian.net/browse/SRE-60

SRE-60 | make CustomizeToolbarTests more stable

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/vet/VetAddVideoComponentObject.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/SpecialVideosPageObject.java

* increase timeout for uploading video (it takes ages in RES)
* make selector more specific—it was including wrong elements
https://wikia-inc.atlassian.net/browse/SRE-90

SRE-90 | fix SpecialVideos tests

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java

Test should later be moved to project43

ADEN-7451 dfpParamsPresentOasis - value updated

---

src/test/java/com/wikia/webdriver/testcases/discussions/NavigatingTests.java

There will be whole local nav suite created.

Remove two navigation tests for Discussions

---

src/test/java/com/wikia/webdriver/common/skin/SkinHelper.java

Renaming skin-desktop to skin-oasis

---

src/test/java/com/wikia/webdriver/elements/communities/mobile/components/PortableInfoboxObject.java
src/test/java/com/wikia/webdriver/testcases/mobile/PortableInfoboxTests.java

Infoboxes Mobile Wiki css fixes

---

src/test/java/com/wikia/webdriver/elements/communities/desktop/components/navigation/local/CommunityHeaderDesktop.java

Update selector for stacked avatars after pulling it from DS

---

src/test/java/com/wikia/webdriver/elements/communities/mobile/pages/ArticlePageObject.java
src/test/java/com/wikia/webdriver/elements/communities/mobile/pages/CommentsPageObject.java
src/test/java/com/wikia/webdriver/testcases/mobile/ArticlePageTests.java
src/test/java/com/wikia/webdriver/testcases/mobile/CommentsTests.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

Mobile Page bottom CSS updates

---

src/test/java/com/wikia/webdriver/elements/communities/mobile/components/SmartBanner.java

@Wikia/x-wing @nikodamn 
This was causing Selenium Tests for smartbanner to fail

SmartBanner | Updating SB to use the new selector

---

src/test/java/com/wikia/webdriver/common/contentpatterns/AdSlot.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsJWPlayerObject.java
src/test/java/com/wikia/webdriver/testcases/desktop/adstests/TestAdsRepeatableIncontentBoxadMobileWiki.java

Fixes for news and stories tests.
JWPlayer play clicked now with offset to prevent clicking of global nav

Aden 7623 News and stories selectors fix

---

src/test/java/com/wikia/webdriver/common/contentpatterns/PageContent.java
src/test/java/com/wikia/webdriver/common/core/api/ArticleContent.java
src/test/java/com/wikia/webdriver/common/core/url/UrlBuilder.java
src/test/java/com/wikia/webdriver/common/dataprovider/FileDataProvider.java
src/test/java/com/wikia/webdriver/testcases/desktop/articlecrudtests/ArticleFeaturesCRUDTestsUser.java
src/test/java/com/wikia/webdriver/testcases/desktop/articlecrudtests/ArticleSourceModeTests.java
src/test/java/com/wikia/webdriver/testcases/desktop/discussions/CommunityHeaderTests.java
src/test/java/com/wikia/webdriver/testcases/desktop/navigation/global/GlobalNavigationSearching.java
src/test/java/com/wikia/webdriver/testcases/mobile/navigation/globalnav/GlobalNavigationMobileWikiTests.java
src/test/resources/TextFiles/Infobox2_Invocation
src/test/resources/TextFiles/Mercury_Gallery
src/test/resources/TextFiles/Mercury_LinkedImages

- Changes with assertions: for better readability
- Adjustments for SZL tests: navigation searching & explore menu

SZL tests for search and explore menu & assertions changes

---

src/test/java/com/wikia/webdriver/testcases/desktop/adstests/TestAdsFandomBtfBlock.java

BTF Block test adjusted to non-sra changes

BTF Block test adjusted to non-sra changes

---

src/test/java/com/wikia/webdriver/elements/communities/desktop/components/articlepreview/MobilePreviewModal.java
src/test/java/com/wikia/webdriver/testcases/desktop/articlepreviewtests/MobilePreviewTests.java
src/test/java/com/wikia/webdriver/testcases/desktop/navigation/local/CommunityHeaderTests.java
src/test/resources/TextFiles/Rich_Article

* Article Mobile preview test should prepare itself's data
* Remove redundant 'de' from CommunityHeader non-english test
@Wikia/iwing @ludwikkazmierczak @sczerwinski-wikia @chessky @swietlana

Refactor article mobile preview tests

---

src/test/java/com/wikia/webdriver/common/core/url/UrlChecker.java
src/test/java/com/wikia/webdriver/testcases/mobile/HeaderTest.java
src/test/java/com/wikia/webdriver/testcases/mobile/RedirectionTests.java
src/test/resources/TextFiles/Infobox1_Invocation
src/test/resources/TextFiles/Infobox1_Template

@sczerwinski-wikia @ludwikkazmierczak @chessky

Url checker & hero image fix

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/editprofile/AvatarComponentObject.java

https://wikia-inc.atlassian.net/browse/SRE-91

SRE-91 | Update avatar modal selector

---

src/test/java/com/wikia/webdriver/elements/communities/mobile/pages/curatedcontent/CuratedMainPagePageObject.java
src/test/java/com/wikia/webdriver/testcases/mobile/curatedcontenttests/CropImageTests.java
src/test/java/com/wikia/webdriver/testcases/mobile/curatedcontenttests/EditorTests.java
src/test/java/com/wikia/webdriver/testcases/mobile/curatedcontenttests/ImageUploadTests.java

Reverts Wikia/selenium-tests#2481

Revert "Curated main page fandom fix"

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/TrackingOptInPage.java
src/test/java/com/wikia/webdriver/testcases/desktop/adstests/TestAdsTrackingOptInRequestsOasis.java

Length of euconsent adjusted
Tracking outside EU is using correct methods

Aden 7846 - tracking fixes

---

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
src/test/java/com/wikia/webdriver/elements/communities/mobile/components/discussions/common/Post.java
src/test/java/com/wikia/webdriver/elements/communities/mobile/components/discussions/common/Replies.java
src/test/java/com/wikia/webdriver/elements/communities/mobile/components/discussions/common/Reply.java
src/test/java/com/wikia/webdriver/testcases/desktop/adstests/TestAdsPrebid.java
src/test/java/com/wikia/webdriver/testcases/mobile/curatedcontenttests/MainPageTests.java

This PR is to the `dev` branch. Since I've created my branch from `master` there are few commits from there, but eventually they'll come to the `dev` too, so please ignore them. 
@swietlana

Opengraph fixes

---

src/test/java/com/wikia/webdriver/elements/communities/mobile/components/discussions/common/category/CategoriesFieldset.java
src/test/java/com/wikia/webdriver/testcases/desktop/discussions/CategoriesTests.java

Discussion desktop categories fixes

---

src/test/java/com/wikia/webdriver/testcases/desktop/discussions/FollowingPostTests.java

Use getFirstPost to get followed post

---

src/test/java/com/wikia/webdriver/testcases/desktop/adstests/TestAdsSkinPresence.java
src/test/java/com/wikia/webdriver/testcases/desktop/adstests/TestAdsTrackingOptInRequestsMobileWiki.java
src/test/java/com/wikia/webdriver/testcases/desktop/adstests/TestAdsTrackingOptInRequestsOasis.java
src/test/java/com/wikia/webdriver/testcases/desktop/adstests/TestDfpParamsPresent.java

ADEN-8242 Ads tests split

---

src/test/java/com/wikia/webdriver/elements/communities/desktop/components/navigation/global/GlobalNavigation.java
src/test/java/com/wikia/webdriver/elements/communities/desktop/components/navigation/local/CommunityHeaderDesktop.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java

Selector changes for avatar icons (loggedIn, loggedOut) and for Explore Menu icon.

Selectors changes due to new icons set

---

src/test/java/com/wikia/webdriver/common/contentpatterns/MobileWikis.java

Change wiki for empty discussions

---

src/test/java/com/wikia/webdriver/common/core/configuration/Configuration.java
src/test/java/com/wikia/webdriver/common/core/url/UrlBuilder.java

- changed UrlBuilder for language annotation - needed to change language into a path
- removed ForceLanguageInPath - we do not run tests on 'szl' anymore
Thank you @ludwikkazmierczak

UrlBuilder adjustments for language annotation

---

src/test/java/com/wikia/webdriver/elements/communities/desktop/components/navigation/global/GlobalNavigation.java
src/test/java/com/wikia/webdriver/testcases/desktop/auth/SignupTests.java
src/test/java/com/wikia/webdriver/testcases/desktop/navigation/global/GlobalNavigationLayout.java

- partner slot removed from test (we don't have this feature any more)
- change in signup tests - temporary fix in test, will revert when services team fix the issue (related issue added in comment)

IW | remove partner slot from test

---

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/anonymization/SpecialAnonymizationUserPage.java
src/test/java/com/wikia/webdriver/testcases/desktop/anonymization/AnonymizationTests.java

Reverts Wikia/selenium-tests#2674

Revert "SER-4086 Disable anonymization tests"

---

src/test/java/com/wikia/webdriver/testcases/desktop/auth/LoginTests.java

Update after https://github.com/Wikia/auth-pages/pull/121/files

IW | invalid pass string update

---

src/test/java/com/wikia/webdriver/common/contentpatterns/URLsContent.java
src/test/java/com/wikia/webdriver/elements/communities/desktop/components/navigation/global/GlobalNavigation.java
src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/widget/PlaybuzzWidgetPageObject.java
src/test/java/com/wikia/webdriver/testcases/desktop/infobox/portableinfoboxtests/PortableInfoboxTests.java
src/test/java/com/wikia/webdriver/testcases/desktop/navigation/global/GlobalNavigationLayout.java
src/test/java/com/wikia/webdriver/testcases/desktop/navigation/global/GlobalNavigationNavigating.java
src/test/java/com/wikia/webdriver/testcases/desktop/navigation/global/GlobalNavigationSearching.java
src/test/java/com/wikia/webdriver/testcases/desktop/navigation/local/CommunityHeaderTests.java
src/test/java/com/wikia/webdriver/testsuites/testSuite.xml

Changed:
- Playbuzz selectors
- some wikis (as previous were already migrated to ucp)
- disable forum tests
- simplify temporarily GlobalNav tests - until there will be a fix (if? since we're moving to ucp)

Test small fixes
