src/test/java/com/wikia/webdriver/common/core/Assertion.java, src/test/java/com/wikia/webdriver/common/core/MailFunctions.java, src/test/java/com/wikia/webdriver/common/core/imageutilities/ImageEditor.java, src/test/java/com/wikia/webdriver/common/core/urlbuilder/UrlBuilder.java, src/test/java/com/wikia/webdriver/common/logging/PageObjectLogging.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/mercury/InteractiveMapsMercuryComponentObject.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/mercury/LightBoxMercuryComponentObject.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/forumpageobject/ForumPageObject.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/mercury/PerformTouchAction.java, src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleCRUDAnonTests.java, src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleCRUDUserTests.java, src/test/java/com/wikia/webdriver/testcases/blogtests/BlogTests.java
Method parameters, caught exceptions and foreach variables should not be reassigned
While it is technically correct to assign to parameters from within method bodies, it is better to use temporary variables to store intermediate results. This rule will typically detect cases where a constructor parameter is assigned to itself instead of a field of the same name, i.e. when this was forgotten. Allowing parameters to be assigned to also reduces the code readability as developers will not be able to know whether the original parameter or some temporary variable is being accessed without going through the whole method. Moreover, some developers might also expect assignments of method parameters to be visible from callers, which is not the case and can confuse them. All parameters should be …
=> QAART-517: Avoided reusing method parameter

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/helpers/AdsComparison.java
We moving 'hide/show slot' functionality from changing visibility to changing opacity because we found one case when changing visibility of slot doesn't hide the ad (if between slot and ad we have items with visibility equals show).
=> ADEN-1743 Change functionality for hiding slot to changing opacity property of the web element.

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/dropdowncomponentobject/DropDownComponentObject.java, src/test/java/com/wikia/webdriver/testcases/facebooktests/FacebookTests.java
Problems:
- When clicking on facebook button via selenium dropdown disappears --> changed to js click (Bogna's idea)
- Double call method Facebook_001_removeWikiaApps --> removed from Facebook_003_linkFBwithWikia
Applied code format for DropDownComponentObject.java and FacebookTests.java
=> Fixed facebook_003 test

src/test/java/com/wikia/webdriver/common/templates/search/IntraWiki.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/search/intrawikisearch/IntraWikiSearchPageObject.java, src/test/java/com/wikia/webdriver/testcases/searchtests/intrawiki/BasicActions.java
1 . searchPageOpened  was deleted earlier this week, but a merge reintroduced it. 
2. anonSearch and userSearch tests are searching were searching for lowerCase letter a, when result was upperCase letter A
PR provides fix for both
1. removes searchPageOpened test
2. changes search query from lower-case to upper-case
=> removig deleted reintroduces search 14 test, changing result string

src/test/java/com/wikia/webdriver/common/dataprovider/VisualEditorDataProvider.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorEditTemplateDialog.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorInsertTemplateDialog.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/visualeditor/VisualEditorPageObject.java, src/test/java/com/wikia/webdriver/testcases/visualeditor/VETemplateTests.java
Added wait for edit template's focus mode for a better transition.
Refactored the method for transclusion to be generic.
Removed the unnecessary try and catch since the test no longer needs to switch back to default content.
=> VE-1878: Updating test for adding and editing templates

src/test/java/com/wikia/webdriver/testcases/interactivemapstests/DeleteAndRestoreMapTests.java
DeleteAndRestoreMapTests_004_StaffUserCanDeleteMap and DeleteAndRestoreMapTests_001_DeleteMapAsAMapOwner are regularly failing because sometimes there is no map to delete since their respective restore tests failed to restore it.
=> Added dependencies on delete and restore tests to assure stability

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/facebook/FacebookSettingsPageObject.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/facebook/RemoveFacebookPageObject.java, src/test/java/com/wikia/webdriver/testcases/facebooktests/FacebookTests.java, src/test/java/com/wikia/webdriver/testcases/signuptests/SignUpTests.java
moved the remove facebook function to it's own page object and added an after method to clean up prefs when test is finished running.
=> Facebook tests - fix for QAART-559

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/editmode/SourceEditModePageObject.java, src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleSourceModeTests.java
The test would fail sometimes if the test tries to click on the submit button when the modal is up. When the modal is up, is when there is a white overlay that is blocking the button. Adding wait for those items to be gone after clicking the button to close the modal.
=> QAART-537 Fix for RTE_019_MoreSympolsTools

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/SpecialNewFilesPageObject.java, src/test/java/com/wikia/webdriver/testcases/imageservingtests/ImageStorageTests.java
The issue with the test failing is because the selector is not targeting the latest file that was uploaded. Since each individual uploaded file has a unique random filename, sometimes when it would select a different file that the value of 'src' would not match.
=> QAART-521: Fixing the ImageStorage001 test

src/test/java/com/wikia/webdriver/common/core/Assertion.java
https://wikia-inc.atlassian.net/browse/QAART-565
Previously if a test fails, it would log the failure then also log the success, this creates double logging and incorrect logging as well.
Also formatted the log output to put double quotes on the parameter passed into the assertion.
=> QAART-565 Removed incorrect double logging in assertion

pom.xml, readme.md, src/test/java/com/wikia/webdriver/common/core/configuration/AbstractConfiguration.java, src/test/java/com/wikia/webdriver/common/core/configuration/ManualConfiguration.java, src/test/java/com/wikia/webdriver/common/core/configuration/POMConfiguration.java, src/test/java/com/wikia/webdriver/common/driverprovider/NewDriverProvider.java
https://wikia-inc.atlassian.net/browse/QAART-568
Disabling Adobe Flash to ensure that FF would exit all of the plugins before the driver exits.
This would make the FF run time to be normal again as org.openqa.selenium.os.UnixProcess$SeleniumWatchDog destroyHarder should no longer happen on Jenkins
=> QAART-568: Adding a parameter to disable Adobe flash (for FF)

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/editmode/SourceEditModePageObject.java
https://wikia-inc.atlassian.net/browse/QAART-574
One of the issues to cause a fail is that if the tool modal is still opened, the focus mode layer would block the interaction of the clicking on the submit button.
Adding wait for the modal and the focus mode to disappear before proceeding of next action.
This should alleviate issues for RTE_017, RTE_018, and RTE_019
=> QAART-574 Fix for RTE_017_MoreMainTools

readme.md, src/test/java/com/wikia/webdriver/common/core/urlbuilder/UrlBuilder.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestUrlBuilder.java
There are two issues currently with running tests for Mercury:
* `useskin=mercury` doesn't work in staging environments, so you can't run tests for this skin for instance on sandboxes,
* while developing we work on local instance of Mercury using [xipio](http://xip.io/) - we can't verify if our changes don't introduce regression because it's impossible to run selenium tests on our local instances of Mercury.
In the changes below I changed `UrlBuilder` in the way which allows us to solve those issues. After merging those changes we should be able to run selenium tests on a local Mercury instance by using `-Dbrowser=CHROMEMOBILEMERCURY` parameter along with `env` parameter set to a devbox name.
Example:
`mvn test -Dgroups=MercuryArticleTests -Dbrowser=CHROMEMOBILEMERCURY -Denv=dev-nandy` …
=> ADEN-1989 Prepare better selenium tests for Mercury

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsKruxObject.java
Krux writes segments for a user to localStorage. We get these segments and pass them to DFP (we send only first 27 segments). Recently due to business reasons we set highest priority for  `ph3uhzc4` segment (It means if a user has 40 segments and `ph3uhzc41` segment is 38th we still send the segment to DFP. This PR stabilises the test due to code changes.
=> ADEN 2001 Set highest priority for ph3uhzc41 segment

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestKruxIntegration.java
We use `popularSites` data provider in the different tests. One of them is a test that checks integration with Krux. The test contains verification that we added Krux data to our Ad slot. So, my PR is about changing one URL from the page where we don't have Ad slot (search page on mobile) to the page which contains an Ad slot (video page).
=> ADEN-2001 Update to page where we have an ad slot

src/test/java/com/wikia/webdriver/common/dataprovider/mobile/MobileAdsDataProvider.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/mobile/MobileAdsBaseObject.java, src/test/java/com/wikia/webdriver/testcases/adstests/mobileadstests/TestAdTypeMobile.java, src/test/java/com/wikia/webdriver/testcases/adstests/mobileadstests/TestDfpParamsPresentMobile.java, src/test/java/com/wikia/webdriver/testcases/adstests/mobileadstests/TestSlotsMobile.java, src/test/java/com/wikia/webdriver/testcases/adstests/mobileadstests/TestSynthetic.java
Mercury is a single page application and it does not behave like regular web page. Therefore we need couple of changes in our mobile tests (`MobileAdsBaseObject::mercuryWaitForPageToLoad()`). There are also some issues with filling ads slots on consecutive pageviews. So, the changes below include new test which is checking ad slots for a synthetic test page, main page and an article page which links can be found on the main page.
The test is failing now but once we find the cause and fix the issue it should start passing :japanese_ogre:
=> ADEN-1989 Test ads on consecutive page views

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java
The test was "fixed" by targeting house ads for the synthetic pages.
But since the safe iframes are being used much more often it seems removing the custom JavaScript and using Selenium driver features instead to check if an iframe is loaded might help. The changes below aren't connected only to the `TestLeaderboardAndPrefooterOnConsecutivePageViews()` test. I'm removing there custom JS and replacing it with the driver's features to switch to the iframe, wait for it to load and then switch back to the default content.
//cc @drets @ludwikkazmierczak
=> ADEN-2036 Fix waitForIframeLoaded()

src/test/java/com/wikia/webdriver/testcases/heromoduletests/HeroModuleTests.java
Tests should be executed in mediawiki119 when possible. This change simply involves deleting momrod2 wiki as the wiki for executing hero module tests. From now on, hero module tests will exclusively run on mediawiki119.
=> Deleting openWikiPage method

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/createnewwiki/CreateNewWikiLogInSignUpPageObject.java, src/test/java/com/wikia/webdriver/testcases/logintests/ForgottenPasswordTests.java
added logic that was initially left out to reset the forgot password timing so that a user can request new password multiple times in a 24 hour period.
=> SOC-843 add logic to reset forgot password time

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java, src/test/java/com/wikia/webdriver/testcases/adstests/mobileadstests/TestSlotsMobile.java
While working on Amazon tests in Mercury we found out waiting for preloader in Mercury isn't good enough. We used this method (`mercuryWaitForPreloaderToHide()`) also in `TestLeaderboardAndPrefooterOnConsecutivePageViews` which started failing today on preview. We decided to get rid of suboptimal method and used `waitTitleChangesTo()` instead.
=> ADEN-2201 Small change in `TestLeaderboardAndPrefooterOnConsecutivePageViews`

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdType.java
We created a new synthetic test for Oasis (`TestAdTypeCollapse_001`) and added it to `TestAdType` group which tests are being ran while executing Jenkins' `ads-mercury-ad-type` job. This job runs only on Mercury skin and this causes failure for the new test.
I renamed the test and excluded it from `TestAdType` group here. After it passes code review, I'm going to create a job in Jenkins to execute only the new synthetic test.
=> ADEN-2186 Fix for ads-mercury-ad-types job in Jenkins

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsScreenshotComparison.java
Resize the browser to 1900x900 so we can run the tests on the regular
machines and not necessarily the high resolution ones.
=> ADEN-2248 Resize the browser window to 1900x900

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/BasePageObject.java
Lest be careful here and wait for the element clickability after we scroll to it.
The scroll may be very fast and timings are unknown so its more safe to wait for the element to be clickable. 
I suspect this wait to be the fix of a failure that I noticed today.
It's very rare failure but this fix may prevent it.
=> wait for element clickability before click

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsInterstitialObject.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsInterstitial.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestInterstitial.java, src/test/java/com/wikia/webdriver/testsuites/testSuite.xml
Many times the interstitial test for scaled content fails because of 1px higher ad content than expected while writing the test.
This change just checks if the "default" (not scaled) version equals exactly the size and then verifies if the scaled version on bigger window is just bigger than default.
=> ADEN-2311 First attempt to make interstitial tests more stable

src/test/java/com/wikia/webdriver/common/core/elemnt/Wait.java, src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
* changed data provider so it follows changes in https://github.com/Wikia/app/pull/8463,
* changed `Wait.forElementPresent()`, so it logs more clear message when test's failing, example:
//cc @ludwikkazmierczak @drets @PiotrGackowski
=> ADEN-2438 Fix hub slot paths

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsAmazonObject.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsGermanObject.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestATF.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdSkinPresence.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsFliteTagOasis.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsMonitoringOasis.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsSlotsOasis.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsSpotlights.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestIncontentBoxad.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestRoadblocksAfterMultiplePageViews.java
Except adaption of ads monitoring tests to creatives with `adType` equals `collapse` I did first small step for refactoring _old_ **awesome** AdsBaseObject:
* removed unused things
* reordered methods: public - up, private/protected - down
* renamed `check*` methods which return `void` to `verify*` for consistency
* and other small tweaks
=> ADEN-2239 Make adType collapse to pass screenshot comparison tests

config_default.yml, src/test/java/com/wikia/webdriver/common/core/configuration/Configuration.java, src/test/java/com/wikia/webdriver/common/core/exceptions/TestEnvInitFailedException.java
Configuration handling:
<ol>
<li>Look for the property key in testConfig map, if key is present, return the value</li>
<li>Look for the property key in system properties - return value of this property if key present
</li>
<li>If no System Property is found - value is provided from configuration files
(config_default.yml and config.yml). Values provided in config.yml, are overriding values from
config_default.yml</li><ol>
<b>ALSO: config_sample.yml becomes config_default.yml</b>
Before the change, you had to copy all the values to config.yml, now you can specify only values that you want to overrride
=> Proper local config overriding

src/test/java/com/wikia/webdriver/common/contentpatterns/MercuryMessages.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/mercury/GalleryComponentObject.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/mercury/LightboxComponentObject.java, src/test/java/com/wikia/webdriver/testcases/mercurytests/LightboxTests.java
Refactoring of lightbox test 004 so that it can be runned on chromemobile mercury.
Adding Gallery Component Object, which should have been used in the test when the driver clicks on gallery image, and then lightbox opens.
=> Moving lightbox test 004 to chromemobile mercury

src/test/java/com/wikia/webdriver/common/core/elemnt/Wait.java, src/test/java/com/wikia/webdriver/common/core/networktrafficinterceptor/NetworkTrafficInterceptor.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsTrackingPixels.java, src/test/java/com/wikia/webdriver/testsuites/testSuite.xml
Current PR adds the test which checks the requests and successful responses for the following services:
* Krux
* Comscore
* Quantqast
on consecutive page views on Oasis and Mercury.
=> ADEN-2596 Add test for tracking pixels

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsKruxObject.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsKruxIntegration.java
* `@UseUnstablePageLoadStrategy` annotation removed.
In this particular test the loading of the page is really matter since KRUX user appended to GPT slot parameters at least after 1st page view.
* `waitForKrux` method removed.
After removing the `@UseUnstablePageLoadStrategy` annotation the execution time of the test increases more than in 3 times.
Removing `waitForKrux` method fixes the execution time issue.
=> ADEN-2604 Make Krux tests more stable

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/mobile/MobileAdsBaseObject.java
The tracking pixels test fails due to flite ad on the page. 
This changes hide flite ad before clicking on article link.
=> ADEN-2636 Hide flite ad if present

src/test/java/com/wikia/webdriver/testcases/logintests/ForgottenPasswordTests.java
This is the exact test case as SpecialPage forgotten password, but the username is lowercase in this added test.  I had to modify the string used to verify since the avatar selector has the first letter capitalized.
=> SOC-1728 add forgotten password test case for lowercase username

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsOoyalaObject.java
Due to last update of Chrome browser we can't easily get `object` DOM elements.
=> ADEN-2724 Fix Ooyala selector

src/test/java/com/wikia/webdriver/common/core/imageutilities/ImageComparison.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsOoyalaObject.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestOoyalaAds.java
While working on this, we ran in to some interesting challenges with video playback inside of different browsers. Much like everything else, browsers render video differently from one another. For example, Chrome may render blue as `3,0,253`, where Firefox will render it as `5,0,253`. This leads to us not being able to comparing exact RGB values and instead finding a way to tell of colors are similar to each other. We did this by comparing the colors in 3d space, inspired by [these answers](http://stackoverflow.com/questions/15262258/how-could-i-compare-colors-in-java) on [Stack Overflow](http://stackoverflow.com/questions/1725505/finding-similar-colors-programatically).
=> VE 2106: Update tests for Ooyala HTML5 player

src/test/java/com/wikia/webdriver/testcases/seotests/HtmlTitleTests.java
* Always use dashes (no more em dashes for some languages)
* Just "Wikia" for corporate home pages
=> HTML title updates

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
Since www.wikia.com has changed to Wordpress, we need to remove tests that check wikia.com as it was MediaWiki.
=> ADEN-2795 remove wikia.com from dataproviders

src/test/java/com/wikia/webdriver/testcases/interactivemapstests/EmbedMapTests.java, src/test/java/com/wikia/webdriver/testcases/interactivemapstests/NonSpecificMapTests.java, src/test/java/com/wikia/webdriver/testcases/interactivemapstests/PinMapTests.java
The tests are being disabled as the maps functionality will be deprecated. Until the feature is fully removed from Wikia then only the core maps functionality tests are required (the required tests being selected by the Content Team).
=> Disabled maps tests according to Rodrogo Molinero and Content team

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsEvolveObject.java
Evolve2 is using DFP and we don't load the script anylonger. Just the id of Evolve's slots is different than Wikia's slots.
=> ADEN-2818 Update the evolve selector

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
`Special:Video` works but it's a redirect to `Special:Videos`. Let's remove the redirect and go straight to the right page.
=> ADEN-2846 Update special page for videos name

src/test/java/com/wikia/webdriver/testcases/specialpagestests/EditingPreferencesTests.java
Added a simple check if 'new email' is not the same as 'current email' - in this situation change will not trigger the mail change confirmation e-mail, and that what was causing the QAART-703 issue.
=> Added a check for current email NOT equals to new email

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java
Since the logic of appending Floating medrec is changed we need to trigger it before looking for an element in the DOM.
**Please, don't merge it before app release (https://github.com/Wikia/app/pull/9433)**
=> ADEN-2712 Update FMR

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java, src/test/java/com/wikia/webdriver/common/dataprovider/mobile/MobileAdsDataProvider.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestDfpParamsPresent.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestDfpParamsPresentMobile.java
Evolve2 provides more parameters in `dfp-slot-params`. We want our test to verify if the params are there as well. We had almost all pieces ready but they needed small customization:
* new data providers which include DFP client id,
* second version of `verifyGptIframe()` which as the first parameter takes the DFP client id,
* new tests run only in NZ.
=> ADEN-2888 Upgrade evolve tests

src/test/java/com/wikia/webdriver/testcases/imageservingtests/ImageStorageTests.java
Just one line fix, but I created PR for you to check if I understand what test should check correctly.
Previously:
Test was uploading image A, then renaming it to B, then trying to open not existing image A and rename it to A again.
Now:
Test is uploading image A, then renaming it to B, then opens image B and renames it to A again.
=> Image serving rename file fix

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/discussions/PostsListPage.java, src/test/java/com/wikia/webdriver/testcases/discussions/Sorting.java
I've removed the check for "trending" and "latest" label as this is not the goal of the functional test. The functional test goal is to check if user can switch between tabs. It doesn't include a test of a "copies".
Both tests were stable in 20 times run verification:
http://jenkins:8080/view/Mercury/job/Mercury-TESTS-Stability/365/
http://jenkins:8080/view/Mercury/job/Mercury-TESTS-Stability/366/
=> adjusting test to the recent sort option change

src/test/java/com/wikia/webdriver/common/dataprovider/VideoUrlProvider.java
According to https://wikia-inc.atlassian.net/browse/SUS-170 we're retiring support for videos from metacafe.com provider, so I removed it from tests.
=> Remove metacafe provider check

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java
In order to make our synthetic tests more stable we want to run them on project43 wiki.
=> ADEN-3148 Move interstitial ads tests from adtest wiki to project43 wiki

src/test/java/com/wikia/webdriver/common/dataprovider/mobile/MobileAdsDataProvider.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsKruxIntegration.java
Because of disabling mercury skin on non supported namespaces (e.g. Special:Videos)
=> ADEN-3173 Exlude test case on non supported page by mercury

src/test/java/com/wikia/webdriver/testcases/globalshortcuts/ActionExplorerTest.java, src/test/java/com/wikia/webdriver/testcases/globalshortcuts/KeyboardShortcutsTest.java
GlobalShortcuts no longer loads for anon users, as such we need to ensure
the tests are run as a logged in user.
/cc @Wikia/spitfires
=> (CE-3667) Require login for all GlobalShortcuts tests

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsDetection.java
The detection domain changes from time to time and there is no reason to check exactly the domain. We just want to be sure the request was sent at all with the right param. The modification below do that.
=> ADEN-3427 Changed pattern for a wiki without recovery enabled

src/test/java/com/wikia/webdriver/testcases/mercurytests/SearchTests.java
It makes error logs more human readable.
=> mercury-search-assertion-fix | assertTrue(…equals()) → assertEquals()

src/test/java/com/wikia/webdriver/elements/mercury/pages/InfoboxBuilderPage.java, src/test/java/com/wikia/webdriver/testcases/infoboxbuilder/InfoboxBuilderTests.java
Problem here was the distance to move element to the top was calculated wrong. In IE if offset Y was negative, dragging action was cancelled.
cc @Wikia/west-wing
=> DAT-4568: Fix verifyReordering test in Infobox Builder

src/test/java/com/wikia/webdriver/testcases/portableinfoboxtests/PortableInfoboxTests.java
Fix test by assertion on lowercased values of variables. Assertion failed when comparing links ".../fandom" with ".../Fandom".
Reviewers:
=> Assert on lowercased strings

src/test/java/com/wikia/webdriver/common/core/annotations/Execute.java, src/test/java/com/wikia/webdriver/common/templates/core/CoreTestTemplate.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsInterstitialObject.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsInterstitial.java, src/test/java/com/wikia/webdriver/testcases/mercurytests/RecentWikiActivityTest.java
Ad covers whole screen so it's not possible to click menu entry point
cc @Wikia/west-wing @drets @PiotrGackowski @ludwikkazmierczak
=> DAT-4565: Mock ads for anon naviagates to RWA from menu test

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/globalnav/GlobalNavigation.java, src/test/java/com/wikia/webdriver/testcases/globalnavigationbar/Navigating.java
* Remove test for unsupported functionality (Wikia logo is now always navigating to Fandom)
* Update selector
Reviewers:
=> Dat 4587 - global navigation bar tests

src/test/java/com/wikia/webdriver/testcases/infoboxbuilder/InfoboxBuilderTests.java, src/test/java/com/wikia/webdriver/testcases/portableinfoboxtests/PortableInfoboxTests.java
Split groups:
- PortableInfoboxTests
- InfoboxBuilderTests
into smaller groups. It will increase stability of these tests. Now, unfortunately, whole group is send to one Jenkins' VM which for larger group of tests (like these mentioned above) is causing a lot of failures related to errors of execution.
Reviewers:
=> Dat 4591 - split groups into smaller ones

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/dropdowncomponentobject/DropDownComponentObject.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/globalnav/GlobalNavigation.java, src/test/java/com/wikia/webdriver/testcases/globalnavigationbar/Layout.java
- Add scrollbar width to desired dimension. Window is resized to that dimension although test is based on viewport size. That's why I decided to add scrollbar width there and put comment.
- Simplify method for opening dropdown component. It caused to wait everytime for 20 s.
Reviewers:
=> Dat 4593 - global navigation layout tests

src/test/java/com/wikia/webdriver/testcases/globalnavigationbar/Layout.java
Change window dimensions to (1044,1024) - safe, additional 20 px for scrollbar width. Test is relying on viewport not the windowsize, so to test 1024 view there's need of adding scrollbar width.
=> Change scrollbar width to 20 px

src/test/java/com/wikia/webdriver/common/dataprovider/mobile/MobileAdsDataProvider.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/BasePageObject.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsSlotsMercury.java
Add two tests which corresponds to move of Mobile Top Leaderboard ad on:
- pages with Infoboxes below the Infobox
- pages without Infoboxes below page header. 
Reviewers:
@Wikia/west-wing @drets @PiotrGackowski
=> Dat 4596 - mobile top leaderboard tests for pages w/o Infobox

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/wam/WamPageObject.java, src/test/java/com/wikia/webdriver/testcases/wampagetests/WamPageTests.java
https://wikia-inc.atlassian.net/browse/SUS-700
The contract changed. The latest day show on the WAM page was _now_, is _2 days ago_. This change updates the tests.
The tests fail for the `master` branch: http://jenkins.wikia-prod:8080/view/Sustaining/view/Sustaining%20Production%20Status/job/sustaining-wam-page-prod/98/
The tests pass for the `SUS-700` branch: http://jenkins.wikia-prod:8080/view/Sustaining/view/Sustaining%20Production%20Status/job/sustaining-wam-page-prod/97/
=> SUS-700 update wam_005_testDatePicker for new contract

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsKruxSegments.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsTrackingPixels.java
The changes mock ads explicitly methods in `TestAdsTrackingPixels` class, so we test pixels with mocked ads served from DFP, not with indirect ads which sometimes can kill our QA VMs.
=> ADEN-3683 Make ads-tracking-pixels-mercury stable

src/test/java/com/wikia/webdriver/common/core/imageutilities/ImageEditor.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/mobile/MobileAdsBaseObject.java
After the change which moved `MOBILE_TOP_LEADERBOARD` below Portable Infobox (PI) our monitoring tests started to fail on some wikis (those with PI enabled).
=> ADEN-3644 Fix for monitoring and infobox change

src/test/java/com/wikia/webdriver/testcases/communitypagetests/CommunityPageSalesPitchDialogTests.java
Tickets: 
* https://wikia-inc.atlassian.net/browse/WW-162
* https://wikia-inc.atlassian.net/browse/WW-124
NCF dialog is disabled so we are disabling its tests.
@Wikia/west-wing @nikodamn
=> WW-162 | disabling tests for NCF dialog

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/wam/WamPageObject.java, src/test/java/com/wikia/webdriver/testcases/wampagetests/WamPageTests.java
https://wikia-inc.atlassian.net/browse/SUS-700
Date picker dialog is not available on WAM page anymore. Currently date can be changed only by replacing date with new one in date input. Also WAM page is deprecated.
PR contains:
* removing test part that changes date by date picker dialog
=> SUS-700 Remove checking date picker dialog in wam page

src/test/java/com/wikia/webdriver/common/dataprovider/VideoUrlProvider.java, src/test/java/com/wikia/webdriver/elements/mercury/pages/InfoboxBuilderPage.java, src/test/java/com/wikia/webdriver/testcases/mediatests/providers/VetProvidersTests.java
https://wikia-inc.atlassian.net/browse/SUS-789
There is a ticket to sunset GameStar video provider support (https://wikia-inc.atlassian.net/browse/SUS-979) and we're not going to fix it, so I removed the test which check GameStar video adding.
=> SUS-789 Remove support for GameStar video provider

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java
Fix for `CreateNewWiki_001_createDeleteWiki` test as it failed when trying to click delete a wiki button from dropdown.
=> Scroll to delete wiki button before click

src/test/java/com/wikia/webdriver/common/dataprovider/ads/AdsDataProvider.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsBtfBlocking.java
- extend method AdsBaseObject.waitForPageLoaded to wait for gpt is loaded
- split tests for project43 and adtest-pluto in order to use mockAds=true on adtest-pluto
=> Aden 3761 wait for page load

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsBaseObject.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsBtfBlocking.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsInterstitial.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsKruxSegments.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsSlotsOasis.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestIVWAnalyticsProvider.java
The PR splits waitForPageLoaded method into 2 version:
* with GPT checking
* without GPT checking
Most of the time GPT checking is useful, but this method is used to check if iframe is loaded as well. Then we shouldn't check for GPT.
=> optionally not check for GPT

src/test/java/com/wikia/webdriver/common/dataprovider/mobile/MobileAdsDataProvider.java, src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsDfpParamsPresentMercury.java, src/test/java/com/wikia/webdriver/testsuites/testSuite.xml
Categories for yugioh.wikia.com has changed. Code changes below address that and also they adjust class and method names to [our convention](https://wikia-inc.atlassian.net/wiki/display/ADEN/Ad+Engineering+Automated+Test+Naming+Convention).
Connected JJB PR: https://github.com/Wikia/jenkins-jobs/pull/121
=> Aden 3941 Yugioh categories change

src/test/java/com/wikia/webdriver/common/contentpatterns/PageContent.java
Do not assume that "Formatting" article always exists. Main_Page is present on all wikis and can be safely used when testing link suggest.
http://jenkins.wikia-prod:8080/view/Staging-test/view/staging/job/staging-forum-staging/lastSuccessfulBuild/artifact/logs/log.html
@ludwikkazmierczak / @nikodamn
=> Change REDIRECT_LINK to a page that always exists

src/test/java/com/wikia/webdriver/common/contentpatterns/WikiTextContent.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/visualeditordialogs/VisualEditorReviewChangesDialog.java
Fix for VisualEditorEditing_003_insertToExistingArticle test
Based on https://www.mediawiki.org/wiki/Help:Formatting preformatted text can be added by starting each new line with a space 
=> WW-246: Add space before preformatted text

src/test/java/com/wikia/webdriver/common/contentpatterns/PageContent.java, src/test/java/com/wikia/webdriver/testcases/articlecrudtests/ArticleSourceModeTests.java
Use [a nice picture of mouse](http://mediawiki119.wikia.com/wiki/File:Image010.jpg) when adding an image in editor's source mode. Image010.jpg exists on both production and staging environment.
This fixes [ArticleSourceModeTests](http://jenkins.wikia-prod:8080/view/Staging-test/view/staging/job/staging-rte-2-staging/lastSuccessfulBuild/artifact/logs/log.html#toc3) on staging.
@ludwikkazmierczak / @nikodamn
=> PageContent.ARTICLESOURCEMODEFILE - use a file that exists on staging

src/test/java/com/wikia/webdriver/common/core/api/ApiCall.java, src/test/java/com/wikia/webdriver/common/core/api/ArticleContent.java, src/test/java/com/wikia/webdriver/common/core/api/TemplateContent.java
Removing declarations of static variables that are already defined in parent class. This fixes recording of URL in the ApiCall.call() method
=> Fix call logging

src/test/java/com/wikia/webdriver/testcases/infoboxbuilder/InfoboxBuilderTests.java
Per conversation with @ludwikkazmierczak we will create a new article to follow the same pattern as in other tests. This it the approach used in other CRUD tests successfully.
Also:
* update RelatedIssue for a test case with a different root cause
=> WW-401 Use a new article when running the template creation test

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/adsbase/AdsRecoveryObject.java
Sometimes we get error:
`org.openqa.selenium.WebDriverException: unknown error: window._sp_.getElementId is not a function`
it might be because of SourcePoint lib is not loaded on time, this change should fix it
=> ADEN-4038 stabilize recovery test

src/test/java/com/wikia/webdriver/testcases/mercurytests/SearchTests.java
* Add `DontRun` annotation and remove these tests from Mercury_Search_002 group (due to found bug with `DontRun` annotation blocking whole test's group).
Reviewers:
@mixth-sense
=> SUS-1151-b add DontRun annotation to two Mercury_Search tests

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/createnewwiki/CreateNewWikiPageObjectStep2.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/createnewwiki/CreateNewWikiPageObjectStep3.java
We style buttons to be design system compliant so this button has additional classes, not only `next`
@Wikia/west-wing @mixth-sense @ludwikkazmierczak @nikodamn
=> Fix next button on the second step of Create New Wiki process

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/special/block/SpecialBlockListPage.java
Running `blockedUserCanCreatePostOnHerMessageWall` MessageWall test (in SUS) from a laptop with Hungarian locale failed for me due to date parsing exception. Let's enforce US locale for parsing date in block list
=> Enforce US locale for date parsing in SpecialBlockListPage::isUserBlocked

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsTrackingPixels.java
allow https tracking on auth pages
=> ADEN | fix: allow https tracking on auth pages

src/test/java/com/wikia/webdriver/common/contentpatterns/MercurySubpages.java, src/test/java/com/wikia/webdriver/common/core/drivers/BrowserAbstract.java, src/test/java/com/wikia/webdriver/common/skin/Skin.java, src/test/java/com/wikia/webdriver/common/skin/SkinHelper.java, src/test/java/com/wikia/webdriver/elements/mercury/components/Navigation.java, src/test/java/com/wikia/webdriver/elements/mercury/components/Search.java, src/test/java/com/wikia/webdriver/elements/mercury/components/TopBar.java, src/test/java/com/wikia/webdriver/elements/mercury/old/curatedcontent/CuratedMainPagePageObject.java, src/test/java/com/wikia/webdriver/elements/mercury/pages/ArticlePage.java, src/test/java/com/wikia/webdriver/elements/mercury/pages/CategoryPage.java, src/test/java/com/wikia/webdriver/elements/mercury/pages/SearchResultsPage.java, src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/GuidelinesPage.java, src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationMercuryTest.java, src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationMercuryTests.java, src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationMobileWikiTest.java, src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationMobileWikiTests.java, src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationTest.java, src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationTests.java, src/test/java/com/wikia/webdriver/testcases/mercurytests/SearchMercuryTests.java, src/test/java/com/wikia/webdriver/testcases/mercurytests/SearchMobileWikiTests.java, src/test/java/com/wikia/webdriver/testcases/mercurytests/SearchTests.java, src/test/java/com/wikia/webdriver/testcases/mercurytests/old/curatedcontenttests/EditorTests.java, src/test/java/com/wikia/webdriver/testcases/mercurytests/old/curatedcontenttests/MainPageTests.java, src/test/java/com/wikia/webdriver/testsuites/testSuite.xml
Mercury handles:
- Discussions
- Image Review
- Curated Content Editor
- Infobox Builder
Mobile Wiki handles:
- Wiki Pages
- Curated Main Pages
- Article Preview
- Mobile Search Results Page (`/search`)
They both use Navigation and Search Suggestions, which share most of the code between apps but differ in the way they handle different routes. E.g. when you're on Discussions (handled by Mercury), open Navigation and click a link to article, you'll have full page reload and Mobile Wiki will be loaded. If you do the same thing while on a different article, you'll stay in the SPA without page reload.
This PR updates tests to check shared features in both apps and make sure that navigation between them works as expected.
@ludwikkazmierczak @kvas-damian @idradm @qaga
=> XW-2817 | Update tests after releasing Mobile Wiki

src/test/java/com/wikia/webdriver/testcases/discussions/UpvotingTests.java
To be fixed properly in https://wikia-inc.atlassian.net/browse/IRIS-4139
=> IRIS-hotfix | moved upvoting tests back to dauto wikia because they don't really work anywhere else

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/global_navitagtion/NotificationsComponentObject.java
Use more specific CSS selector to get bubblesCount for Wall, not for on site notifications
Porting @macbre fix to preview
=> NotificationsComponentObject: fix verifyNotification

src/test/java/com/wikia/webdriver/elements/mercury/components/TopBar.java, src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationMercuryTests.java, src/test/java/com/wikia/webdriver/testcases/mercurytests/NavigationMobileWikiTests.java
Dirty dirty hotfix. Rationale: 
- X-Wing's tests failed because navigation wouldn't open when notifications unread count covers up hamburger menu (opened https://wikia-inc.atlassian.net/browse/IRIS-4302 to address that)
- quick research shows that it is supposedly possible to click such a covered element in Firefox and IE drivers, however I can't switch to run these tests on anything else than Chrome driver, because it's the only one to work with mobile view
- Ticket to switch back to user with notifications when the whole thing is clickable: https://wikia-inc.atlassian.net/browse/IRIS-4303
=> IRIS-dirty-dirty-hotfix | fixes tests for opening navigation in mobile wiki and mobile view in mercury

src/test/java/com/wikia/webdriver/common/contentpatterns/MercurySubpages.java, src/test/java/com/wikia/webdriver/elements/mercury/old/ArticlePageObject.java, src/test/java/com/wikia/webdriver/testcases/mercurytests/old/ArticlePageTests.java, src/test/resources/TextFiles/Mercury_Gallery, src/test/resources/TextFiles/Mercury_LinkedImages, src/test/resources/TextFiles/Mercury_MainPage
* Prepare Mercury Article tests to staging env - tests should prepare data set on it's own, before test's execution.
* Remove PageObjectLogging info, user Assertions on top level
* Tests verified working on production
* There's a bug with URL encoding in Mercury on staging although test code should stay as it is
@ludwikkazmierczak @sczerwinski-wikia
=> Staging article mercury

src/test/java/com/wikia/webdriver/testcases/globalnavigationbar/Navigating.java
After release of FANDOM 2.0 urls changed 
/games -> /topics/games
/movies -> /topics/movies
/tv -> /topics/tv
@Wikia/x-wing
=> Fix fandom links

src/test/java/com/wikia/webdriver/common/core/drivers/browsers/ChromeBrowser.java, src/test/java/com/wikia/webdriver/common/core/helpers/Emulator.java
Cause Google changed their device name map, and now - "GOOGLE NEXUS 5" is just "NEXUS_5" in new chrome 😿
=> Rewritten old mobile emulation devices to an explicit definition

src/test/java/com/wikia/webdriver/testcases/adstests/TestAdsPremiumPrerollMOATTracking.java
Added `QUERY_PARAM_CONTROL_GROUP` in order to keep the test away from the AB bucket.
=> Keep the job blue despite AB experiment

src/test/java/com/wikia/webdriver/common/core/helpers/Emulator.java, src/test/java/com/wikia/webdriver/testcases/discussions/PromotingTests.java
- Andoid app name was FANDOMized, needed to update the test
- Google Play stopped supporting Nexus 5 with Android 4.2, switched to Nexus 5X with Android 6
=> Fix tests for promoting

src/test/java/com/wikia/webdriver/common/templates/core/CoreTestTemplate.java
I noticed that when tests are skipped there is a chromedriver process hanging, together with a browser window. here is the fix for closing all the windows after each class.
=> Fix for hanging browser

src/test/java/com/wikia/webdriver/common/core/helpers/ForgottenPasswordUserFactory.java, src/test/java/com/wikia/webdriver/common/properties/Credentials.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/BasePageObject.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/WikiBasePageObject.java, src/test/java/com/wikia/webdriver/testcases/auth/ForgottenPasswordTests.java
Tests are passing: http://jenkins.wikia-prod:8080/view/Iris/view/preview/job/iris-auth-forgotten-password-preview/327/
Summary of changes:
- FANDOMize email suject
- delete all emails before and after each tests is executed
- users now have dedicated email accounts (https://github.com/Wikia/selenium-config/pull/53) so that it doesn't interrupt other tests
- slight refactoring
=> IRIS-4246 - fixes tests for forgot password flow

src/test/java/com/wikia/webdriver/elements/mercury/old/SignupPageObject.java
Apparently there's a race condition - webdriver sometimes fills the birthday input value before the focus is set to that input. Workaround: clear the field before setting its value
=> Iris-hotfix | fix flaky signup test

src/test/java/com/wikia/webdriver/testcases/discussions/ReportingPostTests.java
This bug: https://wikia-inc.atlassian.net/browse/IRIS-4867 is being caught by 4 different test cases. I marked them with `RelatedIssue` annotation so that we can quickly spot their failure reason in logs
=> IRIS-hotfix | add related issue for bug with caching deleted posts in discussions

src/test/java/com/wikia/webdriver/common/contentpatterns/VideoContent.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/article/editmode/SourceEditModePageObject.java
It's all about comparing video wiki text, e.g. [[File:WikiEvolution - Poznańska Wiki-1354533479|thumb|right|335 px|TestDataCaption1]] ignoring the 1354533479 number.
http://jenkins.wikia-prod:8080/view/Staging/view/core-dashboard/job/staging-core-rte-3/17/
=> Change the way video wiki text is compared in RTE tests

src/test/java/com/wikia/webdriver/testcases/discussions/UploadingImageTests.java
This tests was executed on post details page for postId set up on another community. The fact that it ever passed was pure coincidence
=> IRIS-hotfix | fix broken image upload test

config_default.yml
To be merge today before cut off, it doesn't touch production so it can be merged to master to run selenium tests with new value right after the cut off.
... or to preview to avoid problems on sandboxes
=> Switch selenium tests to new staging url

src/test/java/com/wikia/webdriver/common/templates/core/CoreTestTemplate.java, src/test/java/com/wikia/webdriver/common/testnglisteners/InvokeMethodAdapter.java
Throwing SkipExceptions in "BeforeMethod" in CoreTestTemplate results in skipping other tests using that method
Another way is to set configfailurepolicy=continue
=> Moved DontRun annotation handling to InvokeMethodAdapter

src/test/java/com/wikia/webdriver/elements/mercury/components/Navigation.java
This actually reverts this commit https://github.com/Wikia/selenium-tests/commit/a009ad50b39845e8c1cea2a5d6f27b6e7f53a5c9 
Since `wikia-nav--login` is not present in mobile wiki, but is present in discussions, so almost all login/signup tests are failing.
It'll be better and more consistent to add `wds-icon` class to dicsussions' nav.
=> Restore selector for register button

src/test/java/com/wikia/webdriver/elements/mercury/pages/discussions/GuidelinesPage.java
https://github.com/Wikia/selenium-tests/commit/74c8f62cfdb5f1d21c3ac754c9d3ab8e0e4a991c was introduced as a fix, but actually broke `guidelinesIsNotEmptyOnNewCommunityDiscussionsPage`, so let's revert that first and fix that previously "fixed" test(s) in different way
=> Fix selector for guidelines

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/BasePostsCreator.java, src/test/java/com/wikia/webdriver/testcases/discussions/UploadingImageTests.java
`userCannotUploadUnsupportedImageToTheirPostOnMobile` was randomly failing because error message covered "submit" button for few seconds - we're now waiting for button to be clickable.
=> Fix post image upload test

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/mcfooter/DiscussionCard.java
SCrolling using our method as this one puts the element right under the navigation bar, not at the bottom
=> Platform-3439: Scroll to elements in mc footer

src/test/java/com/wikia/webdriver/testcases/mobilewikitests/HTMLTitleTests.java
These pages aren't in mobile-wiki nor the values are up to date, so the test fails (http://jenkins:8080/view/X-Wing/view/mobile-wiki-sandbox/job/xwing-mobile-wiki-htmlTitleSet-sandbox/). We already test tiles in https://github.com/Wikia/seo-tests/blob/master/iris-test/testsIrisHtmlTitle.py
/cc @nikodamn @qaga
=> Remove title checks for Discussions

src/test/java/com/wikia/webdriver/common/dataprovider/TrackingOptInDataProvider.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/TrackingOptInModal.java, src/test/java/com/wikia/webdriver/testcases/discussions/TrackingOptIn.java, src/test/java/com/wikia/webdriver/testsuites/testSuite.xml
Use already implemented TrackingOptInModal page object and mobile-wiki tests cases in Discussions. Add check for anonymized request to Google Analytics.
@Wikia/iris @ludwikkazmierczak  @bulaszenko @chessky
=> Tracking Opt In in Discussions

src/test/java/com/wikia/webdriver/pageobjectsfactory/componentobject/lightbox/LightboxComponentObject.java
Anons will see a wiki's i18n messages in the content language of the
wiki, so selecting based on the content of an attribute that uses an
i18n message won't work on a non-English wiki such as those in our
language path tests. Additionally, selecting based on a translation
string is brittle, so let's use a class selector here.
/cc @Wikia/core-platform-team
=> (PLATFORM-3465) Fix unpin button selector for non-English wikis

src/test/java/com/wikia/webdriver/elements/mercury/components/discussions/common/category/CategoriesFieldset.java
During global nav work there were some changes in the Discussion's DOM structure. Right now there are two `edit category` buttons, but the one is hided from display. I'm aware that this is a nasty hack, although I'd like to still test this functionality until the Discussion's DOM will be fixed.
=> Add hack until Discussions front end's DOM will be fixed

src/test/java/com/wikia/webdriver/testcases/auth/ForgottenPasswordTests.java, src/test/java/com/wikia/webdriver/testcases/auth/LoginTests.java
Remove auth-related tests which are overkill for functional testing. They are already (and should be) tested on lower level.
=> Remove auth overkill tests on the functional level

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/BasePageObject.java
http://jenkins.wikia-prod:8080/view/Iris/view/discussions-sandbox/job/iris-discussions-promoting-sandbox/76/
Timeout was set to 3000 but it is in seconds so I don't think it was done on purpose.
```
private void waitForLinkOpenedInNewTab(WebElement link) {
int initialTabsNumber = driver.getWindowHandles().size();
link.click();
new WebDriverWait(driver,
TIMEOUT_PAGE_REGISTRATION
).until((Function<WebDriver, Boolean>) input -> getTabsCount() > initialTabsNumber);
}
```
=> Changed TIMEOUT_PAGE_REGISTRATION as it is in seconds

src/test/java/com/wikia/webdriver/common/core/configuration/EnvType.java, src/test/java/com/wikia/webdriver/common/core/url/UrlBuilder.java
When a wiki is on the `FANDOM_EXCULUDED_WIKIS` it should not add `suffix` to the name, or change a domain to `fandom.com`, it's mostly API calls to community.
=> Community should not be served from fandom domain

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/forumpageobject/ForumBoardPage.java, src/test/java/com/wikia/webdriver/testcases/desktop/forumtests/ForumAnonTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/forumtests/ForumBoardTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/forumtests/ForumThreadTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/notificationstests/ForumNotificationsTests.java
Remove Forum highlights support from tests. The feature is due to be sunset in https://github.com/Wikia/app/pull/16455 and it's not actually used in any tests.
=> IW-1372 | Remove Forum highlights feature from tests

src/test/java/com/wikia/webdriver/common/core/configuration/Configuration.java, src/test/java/com/wikia/webdriver/common/core/url/FandomUrlBuilder.java, src/test/java/com/wikia/webdriver/common/core/url/UrlChecker.java, src/test/java/com/wikia/webdriver/testcases/desktop/navigation/global/GlobalNavigationNavigating.java
**Context**
Global Nav tests were updated after Language path work and Fandom.com & Wikia.com domains split. Unfortunately assertion were too env-specific and those tests were working properly for prod only (non-Szl). 
This PR introduces more generic solution of Global Nav assertions using UrlChecker and removing relative path (and `www.` prefix).
Also, one tests has spotted a bug and ticket IW-1607 has been created.
**Reviewers**
@ludwikkazmierczak @chessky @swietlana 
//cc @Wikia/iwing
=> Generic solution for fandom.com and wikia.com global nav tests for various envs

src/test/java/com/wikia/webdriver/testcases/desktop/anonymization/AnonymizationTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/articlecrudtests/ArticleActionsAdminTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/articlecrudtests/ArticleSourceModeTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/auth/ForcedLoginTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/auth/LoginTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/auth/SignupTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/commentstests/ArticleCommentsTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/commentstests/BlogCommentsTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/discussions/CommunityHeaderTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/forumtests/ForumBoardTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/globalshortcuts/KeyboardShortcutsTest.java, src/test/java/com/wikia/webdriver/testcases/desktop/mcfootertests/EnAnonMixedContentFooterTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/mcfootertests/NonEnAnonMixedContentFooterTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/navigation/global/GlobalNavigationLayout.java, src/test/java/com/wikia/webdriver/testcases/desktop/navigation/global/GlobalNavigationNavigating.java, src/test/java/com/wikia/webdriver/testcases/desktop/navigation/global/GlobalNavigationSearching.java, src/test/java/com/wikia/webdriver/testcases/desktop/navigation/local/CommunityHeaderTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/renametool/RenameToolTests.java, src/test/java/com/wikia/webdriver/testcases/mobile/CommentsTests.java, src/test/java/com/wikia/webdriver/testcases/mobile/HTMLTitleTests.java, src/test/java/com/wikia/webdriver/testcases/mobile/curatedcontenttests/NavigationTests.java, src/test/java/com/wikia/webdriver/testcases/mobile/navigation/globalnav/GlobalNavigationMobileWikiTests.java
- Deleted tests for `language = 'szl'`
- Deleted RunOnly & DontRun annotation
=> IW-1934 | Get rid of SZL tests and annotations

src/test/java/com/wikia/webdriver/common/contentpatterns/URLsContent.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/wam/WamPageObject.java, src/test/java/com/wikia/webdriver/testcases/desktop/wampagetests/WamPageTests.java
Switches WAM tests to execute on fandom domain instead of wikia.org
Adds simple URL checks (fandom WAM, selected vertical)  and updates date picker test to take into account 0-3 bulkimporter lag.
Adds more checks for order of entries by rank (as it's failing on subpages), also on specific failing date.
=> DE-4387-WAM-tests-on-fandom

src/test/resources/TextFiles/Infobox1_Invocation
Since `www.wikia.com/Fandom` has been changed to `www.fandom.com` one PortableInfobox test is failing.
@Wikia/iwing
=> Update Infobox1 invocation with internal fandom.com link

src/test/java/com/wikia/webdriver/testcases/desktop/articlepreviewtests/MobilePreviewTests.java, src/test/java/com/wikia/webdriver/testcases/desktop/infobox/portableinfoboxtests/PortableInfoboxTests.java, src/test/java/com/wikia/webdriver/testcases/mobile/FilePageTests.java, src/test/java/com/wikia/webdriver/testcases/mobile/HTMLTitleTests.java
What have changed:
- Collapsible sections doesn't work, so I've commented out the Assertions connected with that.
- Infoboxes - somebody created an additional infobox on our testing wiki and even after deleting this infobox it's still visible on the list in the Editor.
- FilePage - platform changed the way how we show the FilePages - it cannot be visible for anons. If there is an article where this file was linked, it's automatically shown to anon.
- HTML title changed due to rebranding
=> IW update tests

src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/wam/WamPageObject.java, src/test/java/com/wikia/webdriver/pageobjectsfactory/pageobject/wam/WamTab.java, src/test/java/com/wikia/webdriver/testcases/desktop/wampagetests/WamPageTests.java
Anime vertical in WAM is not yet filled with data and that's by design.
Still, tests failed due to lack of data in this vertical.
In this commit we make sure that tests ignore Anime vertical.
=> Ignoring ANIME vertical in WAM tests

src/test/java/com/wikia/webdriver/testcases/desktop/wampagetests/WamPageTests.java
Previously, WAM tab was discarded from the test as the data was empty (by design).
Now the tests check if the data is present in this tab as well
=> ANIME tab is included in WAM tests

src/test/java/com/wikia/webdriver/testcases/desktop/analyticstests/AnalyticsPageTests.java
Tested wikia (muppets) was moved to UCP and it caused tests to fail. Now testing on sydneybuses.
https://wikia-inc.atlassian.net/browse/DE-5225
=> DE-5225 | muppet to sydneybuses

src/test/java/com/wikia/webdriver/testcases/desktop/analyticstests/AnalyticsPageTests.java
https://wikia-inc.atlassian.net/browse/DE-5334
SpecialAnalytics page tests are failing because `sydneybuses` wiki was moved to UCP. Changed to `community`.
=> DE-5334 | SpecialAnalytics tests are failing
